// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchInsertPlays implements pgx.CopyFromSource.
type iteratorForBatchInsertPlays struct {
	rows                 []BatchInsertPlaysParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertPlays) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertPlays) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].TrackID,
		r.rows[0].City,
		r.rows[0].Region,
		r.rows[0].Country,
		r.rows[0].Latitude,
		r.rows[0].Longitude,
		r.rows[0].PlayedAt,
		r.rows[0].ListenedAt,
		r.rows[0].RecordedAt,
		r.rows[0].BlockHeight,
		r.rows[0].TxHash,
	}, nil
}

func (r iteratorForBatchInsertPlays) Err() error {
	return nil
}

func (q *Queries) BatchInsertPlays(ctx context.Context, arg []BatchInsertPlaysParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"plays"}, []string{"user_id", "track_id", "city", "region", "country", "latitude", "longitude", "played_at", "listened_at", "recorded_at", "block_height", "tx_hash"}, &iteratorForBatchInsertPlays{rows: arg})
}

// iteratorForBatchInsertSLANodeReports implements pgx.CopyFromSource.
type iteratorForBatchInsertSLANodeReports struct {
	rows                 []BatchInsertSLANodeReportsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertSLANodeReports) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertSLANodeReports) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SlaRollupID,
		r.rows[0].ValidatorAddress,
		r.rows[0].NumBlocksProposed,
		r.rows[0].ChallengesReceived,
		r.rows[0].ChallengesFailed,
	}, nil
}

func (r iteratorForBatchInsertSLANodeReports) Err() error {
	return nil
}

func (q *Queries) BatchInsertSLANodeReports(ctx context.Context, arg []BatchInsertSLANodeReportsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"sla_node_reports"}, []string{"sla_rollup_id", "validator_address", "num_blocks_proposed", "challenges_received", "challenges_failed"}, &iteratorForBatchInsertSLANodeReports{rows: arg})
}

// iteratorForBatchInsertTransactions implements pgx.CopyFromSource.
type iteratorForBatchInsertTransactions struct {
	rows                 []BatchInsertTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TxHash,
		r.rows[0].BlockHeight,
		r.rows[0].TxIndex,
		r.rows[0].TxType,
		r.rows[0].Proposer,
		r.rows[0].Sender,
		r.rows[0].Data,
	}, nil
}

func (r iteratorForBatchInsertTransactions) Err() error {
	return nil
}

// ========================================
// batch operations
// ========================================
func (q *Queries) BatchInsertTransactions(ctx context.Context, arg []BatchInsertTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"tx_hash", "block_height", "tx_index", "tx_type", "proposer", "sender", "data"}, &iteratorForBatchInsertTransactions{rows: arg})
}
