// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	Address string      `json:"address"`
	UserID  pgtype.Text `json:"user_id"`
}

type Block struct {
	Height          int64            `json:"height"`
	Hash            string           `json:"hash"`
	BlockTime       pgtype.Timestamp `json:"block_time"`
	ProposerAddress string           `json:"proposer_address"`
	Data            []byte           `json:"data"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type ChainStat struct {
	ID                  int32            `json:"id"`
	LatestBlockHeight   int64            `json:"latest_block_height"`
	LatestBlockHash     pgtype.Text      `json:"latest_block_hash"`
	LatestBlockTime     pgtype.Timestamp `json:"latest_block_time"`
	TotalTransactions   int64            `json:"total_transactions"`
	TotalValidators     int32            `json:"total_validators"`
	ActiveValidators    int32            `json:"active_validators"`
	AvgBlockTimeSeconds pgtype.Numeric   `json:"avg_block_time_seconds"`
	Transactions24h     int64            `json:"transactions_24h"`
	Transactions7d      int64            `json:"transactions_7d"`
	Transactions30d     int64            `json:"transactions_30d"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type IndexerState struct {
	IndexerName      string           `json:"indexer_name"`
	LastIndexedBlock int64            `json:"last_indexed_block"`
	TargetBlock      int64            `json:"target_block"`
	Status           string           `json:"status"`
	ErrorMessage     pgtype.Text      `json:"error_message"`
	BatchSize        int32            `json:"batch_size"`
	LastRunAt        pgtype.Timestamp `json:"last_run_at"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type ManageEntity struct {
	ID          int32            `json:"id"`
	Address     string           `json:"address"`
	EntityType  string           `json:"entity_type"`
	EntityID    int64            `json:"entity_id"`
	Action      string           `json:"action"`
	Metadata    []byte           `json:"metadata"`
	Signature   string           `json:"signature"`
	Signer      string           `json:"signer"`
	Nonce       string           `json:"nonce"`
	BlockHeight int64            `json:"block_height"`
	TxHash      string           `json:"tx_hash"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Play struct {
	ID          int32            `json:"id"`
	UserID      string           `json:"user_id"`
	TrackID     string           `json:"track_id"`
	City        string           `json:"city"`
	Region      string           `json:"region"`
	Country     string           `json:"country"`
	Latitude    pgtype.Numeric   `json:"latitude"`
	Longitude   pgtype.Numeric   `json:"longitude"`
	PlayedAt    pgtype.Timestamp `json:"played_at"`
	ListenedAt  pgtype.Timestamp `json:"listened_at"`
	RecordedAt  pgtype.Timestamp `json:"recorded_at"`
	BlockHeight int64            `json:"block_height"`
	TxHash      string           `json:"tx_hash"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type SlaNodeReport struct {
	ID                 int32            `json:"id"`
	SlaRollupID        int32            `json:"sla_rollup_id"`
	ValidatorAddress   string           `json:"validator_address"`
	NumBlocksProposed  int32            `json:"num_blocks_proposed"`
	ChallengesReceived int32            `json:"challenges_received"`
	ChallengesFailed   int32            `json:"challenges_failed"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type SlaRollup struct {
	ID             int32            `json:"id"`
	BlockStart     int64            `json:"block_start"`
	BlockEnd       int64            `json:"block_end"`
	ValidatorCount int32            `json:"validator_count"`
	BlockQuota     int32            `json:"block_quota"`
	TxHash         string           `json:"tx_hash"`
	BlockHeight    int64            `json:"block_height"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type StorageProof struct {
	ID            int32            `json:"id"`
	ProverAddress string           `json:"prover_address"`
	ChallengeID   string           `json:"challenge_id"`
	ProofData     []byte           `json:"proof_data"`
	BlockHeight   int64            `json:"block_height"`
	TxHash        string           `json:"tx_hash"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type StorageProofVerification struct {
	ID               int32            `json:"id"`
	ChallengeID      string           `json:"challenge_id"`
	VerifierAddress  string           `json:"verifier_address"`
	IsValid          bool             `json:"is_valid"`
	VerificationData []byte           `json:"verification_data"`
	BlockHeight      int64            `json:"block_height"`
	TxHash           string           `json:"tx_hash"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type Transaction struct {
	ID          pgtype.Int4      `json:"id"`
	TxHash      string           `json:"tx_hash"`
	BlockHeight int64            `json:"block_height"`
	TxIndex     int32            `json:"tx_index"`
	TxType      string           `json:"tx_type"`
	Proposer    string           `json:"proposer"`
	Sender      string           `json:"sender"`
	Data        []byte           `json:"data"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type TransactionTypeStat struct {
	TxType            string           `json:"tx_type"`
	TotalCount        int64            `json:"total_count"`
	LatestTransaction pgtype.Timestamp `json:"latest_transaction"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type TransactionWindow struct {
	TxHash    string           `json:"tx_hash"`
	TxType    string           `json:"tx_type"`
	BlockTime pgtype.Timestamp `json:"block_time"`
}

type Validator struct {
	Address        string           `json:"address"`
	CometAddress   string           `json:"comet_address"`
	Endpoint       string           `json:"endpoint"`
	NodeType       string           `json:"node_type"`
	Spid           string           `json:"spid"`
	VotingPower    int64            `json:"voting_power"`
	Status         string           `json:"status"`
	RegisteredAt   int64            `json:"registered_at"`
	DeregisteredAt pgtype.Int8      `json:"deregistered_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type ValidatorEvent struct {
	ID               int32            `json:"id"`
	ValidatorAddress string           `json:"validator_address"`
	EventType        string           `json:"event_type"`
	BlockHeight      int64            `json:"block_height"`
	TxHash           string           `json:"tx_hash"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type ValidatorStat struct {
	ValidatorAddress        string           `json:"validator_address"`
	TotalBlocksProposed     int64            `json:"total_blocks_proposed"`
	TotalSlaRollups         int32            `json:"total_sla_rollups"`
	SlaRollupsPassed        int32            `json:"sla_rollups_passed"`
	SlaRollupsFailed        int32            `json:"sla_rollups_failed"`
	LastBlockProposedHeight pgtype.Int8      `json:"last_block_proposed_height"`
	LastSlaRollupID         pgtype.Int4      `json:"last_sla_rollup_id"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}
