// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlocks = `-- name: CountBlocks :one
select count(*) from blocks
`

func (q *Queries) CountBlocks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlocks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSLARollups = `-- name: CountSLARollups :one
select count(*) from sla_rollups
`

func (q *Queries) CountSLARollups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSLARollups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactions = `-- name: CountTransactions :one
select count(*) from transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByBlock = `-- name: CountTransactionsByBlock :one
select count(*) from transactions
where block_height = $1
`

func (q *Queries) CountTransactionsByBlock(ctx context.Context, blockHeight int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByBlock, blockHeight)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidators = `-- name: CountValidators :one
select count(*) from validators
`

func (q *Queries) CountValidators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countValidators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidatorsByStatus = `-- name: CountValidatorsByStatus :one
select count(*) from validators where status = $1
`

func (q *Queries) CountValidatorsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countValidatorsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filterValidatorsByEndpoint = `-- name: FilterValidatorsByEndpoint :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
where endpoint like '%' || $1 || '%'
  and ($2::text is null or status = $2)
order by voting_power desc
limit $3 offset $4
`

type FilterValidatorsByEndpointParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Column2 string      `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) FilterValidatorsByEndpoint(ctx context.Context, arg FilterValidatorsByEndpointParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, filterValidatorsByEndpoint,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccount = `-- name: GetAccount :one

select address, user_id from accounts where address = $1
`

// ========================================
// accounts queries
// ========================================
func (q *Queries) GetAccount(ctx context.Context, address string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, address)
	var i Account
	err := row.Scan(&i.Address, &i.UserID)
	return i, err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
select address, user_id from accounts where user_id = $1
`

func (q *Queries) GetAccountByUserID(ctx context.Context, userID pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserID, userID)
	var i Account
	err := row.Scan(&i.Address, &i.UserID)
	return i, err
}

const getActiveValidatorCount = `-- name: GetActiveValidatorCount :one
select count(*) from validators where status = 'active'
`

func (q *Queries) GetActiveValidatorCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveValidatorCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveValidators = `-- name: GetActiveValidators :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
where status = 'active'
order by voting_power desc
limit $1 offset $2
`

type GetActiveValidatorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetActiveValidators(ctx context.Context, arg GetActiveValidatorsParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, getActiveValidators, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlock = `-- name: GetBlock :one

select height, hash, block_time, proposer_address, data, created_at from blocks where height = $1
`

// ========================================
// blocks queries
// ========================================
func (q *Queries) GetBlock(ctx context.Context, height int64) (Block, error) {
	row := q.db.QueryRow(ctx, getBlock, height)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.BlockTime,
		&i.ProposerAddress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockByHash = `-- name: GetBlockByHash :one
select height, hash, block_time, proposer_address, data, created_at from blocks where hash = $1
`

func (q *Queries) GetBlockByHash(ctx context.Context, hash string) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByHash, hash)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.BlockTime,
		&i.ProposerAddress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockByHeight = `-- name: GetBlockByHeight :one
select height, hash, block_time, proposer_address, data, created_at from blocks where height = $1
`

func (q *Queries) GetBlockByHeight(ctx context.Context, height int64) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByHeight, height)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.BlockTime,
		&i.ProposerAddress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockTransactionCount = `-- name: GetBlockTransactionCount :one
select count(*) from transactions where block_height = $1
`

func (q *Queries) GetBlockTransactionCount(ctx context.Context, blockHeight int64) (int64, error) {
	row := q.db.QueryRow(ctx, getBlockTransactionCount, blockHeight)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBlocksByPage = `-- name: GetBlocksByPage :many
select height, hash, block_time, proposer_address, data, created_at from blocks
order by height desc
limit $1 offset $2
`

type GetBlocksByPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetBlocksByPage(ctx context.Context, arg GetBlocksByPageParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, getBlocksByPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.BlockTime,
			&i.ProposerAddress,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChainStats = `-- name: GetChainStats :one
select id, latest_block_height, latest_block_hash, latest_block_time, total_transactions, total_validators, active_validators, avg_block_time_seconds, transactions_24h, transactions_7d, transactions_30d, updated_at from chain_stats where id = 1
`

func (q *Queries) GetChainStats(ctx context.Context) (ChainStat, error) {
	row := q.db.QueryRow(ctx, getChainStats)
	var i ChainStat
	err := row.Scan(
		&i.ID,
		&i.LatestBlockHeight,
		&i.LatestBlockHash,
		&i.LatestBlockTime,
		&i.TotalTransactions,
		&i.TotalValidators,
		&i.ActiveValidators,
		&i.AvgBlockTimeSeconds,
		&i.Transactions24h,
		&i.Transactions7d,
		&i.Transactions30d,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeStatisticsForBlockRange = `-- name: GetChallengeStatisticsForBlockRange :many
select
    snr.validator_address as address,
    sum(snr.challenges_received) as challenges_received,
    sum(snr.challenges_failed) as challenges_failed
from sla_node_reports snr
join sla_rollups sr on sr.id = snr.sla_rollup_id
where sr.block_start >= $1 and sr.block_end <= $2
group by snr.validator_address
`

type GetChallengeStatisticsForBlockRangeParams struct {
	BlockStart int64 `json:"block_start"`
	BlockEnd   int64 `json:"block_end"`
}

type GetChallengeStatisticsForBlockRangeRow struct {
	Address            string `json:"address"`
	ChallengesReceived int64  `json:"challenges_received"`
	ChallengesFailed   int64  `json:"challenges_failed"`
}

// Get challenge statistics for validators in a block range
func (q *Queries) GetChallengeStatisticsForBlockRange(ctx context.Context, arg GetChallengeStatisticsForBlockRangeParams) ([]GetChallengeStatisticsForBlockRangeRow, error) {
	rows, err := q.db.Query(ctx, getChallengeStatisticsForBlockRange, arg.BlockStart, arg.BlockEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChallengeStatisticsForBlockRangeRow
	for rows.Next() {
		var i GetChallengeStatisticsForBlockRangeRow
		if err := rows.Scan(&i.Address, &i.ChallengesReceived, &i.ChallengesFailed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
select
    cs.latest_block_height,
    cs.latest_block_hash,
    cs.latest_block_time,
    cs.total_transactions,
    cs.total_validators,
    cs.active_validators,
    cs.avg_block_time_seconds,
    cs.transactions_24h,
    cs.transactions_7d,
    cs.transactions_30d,
    (select count(*) from validators where status = 'active') as current_active_validators
from chain_stats cs
where cs.id = 1
`

type GetDashboardStatsRow struct {
	LatestBlockHeight       int64            `json:"latest_block_height"`
	LatestBlockHash         pgtype.Text      `json:"latest_block_hash"`
	LatestBlockTime         pgtype.Timestamp `json:"latest_block_time"`
	TotalTransactions       int64            `json:"total_transactions"`
	TotalValidators         int32            `json:"total_validators"`
	ActiveValidators        int32            `json:"active_validators"`
	AvgBlockTimeSeconds     pgtype.Numeric   `json:"avg_block_time_seconds"`
	Transactions24h         int64            `json:"transactions_24h"`
	Transactions7d          int64            `json:"transactions_7d"`
	Transactions30d         int64            `json:"transactions_30d"`
	CurrentActiveValidators int64            `json:"current_active_validators"`
}

// Consolidated query for dashboard statistics
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.LatestBlockHeight,
		&i.LatestBlockHash,
		&i.LatestBlockTime,
		&i.TotalTransactions,
		&i.TotalValidators,
		&i.ActiveValidators,
		&i.AvgBlockTimeSeconds,
		&i.Transactions24h,
		&i.Transactions7d,
		&i.Transactions30d,
		&i.CurrentActiveValidators,
	)
	return i, err
}

const getDashboardTransactionStats = `-- name: GetDashboardTransactionStats :one
select
    total_transactions,
    transactions_24h,
    transactions_24h as transactions_previous_24h, -- placeholder
    transactions_7d,
    transactions_30d
from chain_stats
where id = 1
`

type GetDashboardTransactionStatsRow struct {
	TotalTransactions       int64 `json:"total_transactions"`
	Transactions24h         int64 `json:"transactions_24h"`
	TransactionsPrevious24h int64 `json:"transactions_previous_24h"`
	Transactions7d          int64 `json:"transactions_7d"`
	Transactions30d         int64 `json:"transactions_30d"`
}

func (q *Queries) GetDashboardTransactionStats(ctx context.Context) (GetDashboardTransactionStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardTransactionStats)
	var i GetDashboardTransactionStatsRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.Transactions24h,
		&i.TransactionsPrevious24h,
		&i.Transactions7d,
		&i.Transactions30d,
	)
	return i, err
}

const getDashboardTransactionTypes = `-- name: GetDashboardTransactionTypes :many
select
    tx_type,
    total_count as transaction_count
from transaction_type_stats
order by total_count desc
`

type GetDashboardTransactionTypesRow struct {
	TxType           string `json:"tx_type"`
	TransactionCount int64  `json:"transaction_count"`
}

func (q *Queries) GetDashboardTransactionTypes(ctx context.Context) ([]GetDashboardTransactionTypesRow, error) {
	rows, err := q.db.Query(ctx, getDashboardTransactionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardTransactionTypesRow
	for rows.Next() {
		var i GetDashboardTransactionTypesRow
		if err := rows.Scan(&i.TxType, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHealthyValidatorCountsForRollups = `-- name: GetHealthyValidatorCountsForRollups :many
select
    sr.id as rollup_id,
    count(distinct snr.validator_address) filter (
        where snr.num_blocks_proposed >= (sr.block_quota * 0.8)
          and (snr.challenges_received = 0 or
               (1.0 - (snr.challenges_failed::float / snr.challenges_received)) >= 0.8)
    ) as healthy_validators
from sla_rollups sr
left join sla_node_reports snr on snr.sla_rollup_id = sr.id
where sr.id = any($1::int[])
group by sr.id
`

type GetHealthyValidatorCountsForRollupsRow struct {
	RollupID          int32 `json:"rollup_id"`
	HealthyValidators int64 `json:"healthy_validators"`
}

func (q *Queries) GetHealthyValidatorCountsForRollups(ctx context.Context, dollar_1 []int32) ([]GetHealthyValidatorCountsForRollupsRow, error) {
	rows, err := q.db.Query(ctx, getHealthyValidatorCountsForRollups, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHealthyValidatorCountsForRollupsRow
	for rows.Next() {
		var i GetHealthyValidatorCountsForRollupsRow
		if err := rows.Scan(&i.RollupID, &i.HealthyValidators); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBlock = `-- name: GetLatestBlock :one
select height, hash, block_time, proposer_address, data, created_at from blocks order by height desc limit 1
`

func (q *Queries) GetLatestBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRow(ctx, getLatestBlock)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.BlockTime,
		&i.ProposerAddress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestIndexedBlock = `-- name: GetLatestIndexedBlock :one

select coalesce(max(height), 0) from blocks
`

// ========================================
// dashboard queries
// ========================================
func (q *Queries) GetLatestIndexedBlock(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLatestIndexedBlock)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getLatestSLARollup = `-- name: GetLatestSLARollup :one
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups
order by id desc
limit 1
`

func (q *Queries) GetLatestSLARollup(ctx context.Context) (SlaRollup, error) {
	row := q.db.QueryRow(ctx, getLatestSLARollup)
	var i SlaRollup
	err := row.Scan(
		&i.ID,
		&i.BlockStart,
		&i.BlockEnd,
		&i.ValidatorCount,
		&i.BlockQuota,
		&i.TxHash,
		&i.BlockHeight,
		&i.CreatedAt,
	)
	return i, err
}

const getManageEntitiesByAddress = `-- name: GetManageEntitiesByAddress :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where address = $1
order by created_at desc
limit $2 offset $3
`

type GetManageEntitiesByAddressParams struct {
	Address string `json:"address"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetManageEntitiesByAddress(ctx context.Context, arg GetManageEntitiesByAddressParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByAddress, arg.Address, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntitiesByAddressAndType = `-- name: GetManageEntitiesByAddressAndType :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where address = $1 and entity_type = $2
order by created_at desc
limit $3 offset $4
`

type GetManageEntitiesByAddressAndTypeParams struct {
	Address    string `json:"address"`
	EntityType string `json:"entity_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetManageEntitiesByAddressAndType(ctx context.Context, arg GetManageEntitiesByAddressAndTypeParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByAddressAndType,
		arg.Address,
		arg.EntityType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntitiesByEntity = `-- name: GetManageEntitiesByEntity :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where entity_type = $1 and entity_id = $2
order by created_at desc
limit $3
`

type GetManageEntitiesByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetManageEntitiesByEntity(ctx context.Context, arg GetManageEntitiesByEntityParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntitiesByType = `-- name: GetManageEntitiesByType :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where entity_type = $1
order by created_at desc
limit $2 offset $3
`

type GetManageEntitiesByTypeParams struct {
	EntityType string `json:"entity_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetManageEntitiesByType(ctx context.Context, arg GetManageEntitiesByTypeParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByType, arg.EntityType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntity = `-- name: GetManageEntity :one

select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities where id = $1
`

// ========================================
// manage entities queries
// ========================================
func (q *Queries) GetManageEntity(ctx context.Context, id int32) (ManageEntity, error) {
	row := q.db.QueryRow(ctx, getManageEntity, id)
	var i ManageEntity
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Metadata,
		&i.Signature,
		&i.Signer,
		&i.Nonce,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getManageEntityByTxHash = `-- name: GetManageEntityByTxHash :one
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities where tx_hash = $1
`

func (q *Queries) GetManageEntityByTxHash(ctx context.Context, txHash string) (ManageEntity, error) {
	row := q.db.QueryRow(ctx, getManageEntityByTxHash, txHash)
	var i ManageEntity
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Metadata,
		&i.Signature,
		&i.Signer,
		&i.Nonce,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPlay = `-- name: GetPlay :one

select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays where id = $1
`

// ========================================
// plays queries
// ========================================
func (q *Queries) GetPlay(ctx context.Context, id int32) (Play, error) {
	row := q.db.QueryRow(ctx, getPlay, id)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.City,
		&i.Region,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.PlayedAt,
		&i.ListenedAt,
		&i.RecordedAt,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaysByCountry = `-- name: GetPlaysByCountry :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
where country = $1
order by played_at desc
limit $2 offset $3
`

type GetPlaysByCountryParams struct {
	Country string `json:"country"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetPlaysByCountry(ctx context.Context, arg GetPlaysByCountryParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, getPlaysByCountry, arg.Country, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaysByTrack = `-- name: GetPlaysByTrack :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
where track_id = $1
order by played_at desc
limit $2 offset $3
`

type GetPlaysByTrackParams struct {
	TrackID string `json:"track_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetPlaysByTrack(ctx context.Context, arg GetPlaysByTrackParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, getPlaysByTrack, arg.TrackID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaysByTxHash = `-- name: GetPlaysByTxHash :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
where tx_hash = $1
order by played_at desc
`

func (q *Queries) GetPlaysByTxHash(ctx context.Context, txHash string) ([]Play, error) {
	rows, err := q.db.Query(ctx, getPlaysByTxHash, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaysByUser = `-- name: GetPlaysByUser :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
where user_id = $1
order by played_at desc
limit $2 offset $3
`

type GetPlaysByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetPlaysByUser(ctx context.Context, arg GetPlaysByUserParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, getPlaysByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentBlocks = `-- name: GetRecentBlocks :many
select height, hash, block_time, proposer_address, data, created_at from blocks
order by height desc
limit $1
`

func (q *Queries) GetRecentBlocks(ctx context.Context, limit int32) ([]Block, error) {
	rows, err := q.db.Query(ctx, getRecentBlocks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.BlockTime,
			&i.ProposerAddress,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPlays = `-- name: GetRecentPlays :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
order by played_at desc
limit $1
`

func (q *Queries) GetRecentPlays(ctx context.Context, limit int32) ([]Play, error) {
	rows, err := q.db.Query(ctx, getRecentPlays, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSLANodeReportsForValidator = `-- name: GetRecentSLANodeReportsForValidator :many
select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where validator_address = $1
order by sla_rollup_id desc
limit $2
`

type GetRecentSLANodeReportsForValidatorParams struct {
	ValidatorAddress string `json:"validator_address"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) GetRecentSLANodeReportsForValidator(ctx context.Context, arg GetRecentSLANodeReportsForValidatorParams) ([]SlaNodeReport, error) {
	rows, err := q.db.Query(ctx, getRecentSLANodeReportsForValidator, arg.ValidatorAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaNodeReport
	for rows.Next() {
		var i SlaNodeReport
		if err := rows.Scan(
			&i.ID,
			&i.SlaRollupID,
			&i.ValidatorAddress,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSLARollups = `-- name: GetRecentSLARollups :many
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups
order by id desc
limit $1
`

func (q *Queries) GetRecentSLARollups(ctx context.Context, limit int32) ([]SlaRollup, error) {
	rows, err := q.db.Query(ctx, getRecentSLARollups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaRollup
	for rows.Next() {
		var i SlaRollup
		if err := rows.Scan(
			&i.ID,
			&i.BlockStart,
			&i.BlockEnd,
			&i.ValidatorCount,
			&i.BlockQuota,
			&i.TxHash,
			&i.BlockHeight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTransactions = `-- name: GetRecentTransactions :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
order by created_at desc
limit $1
`

func (q *Queries) GetRecentTransactions(ctx context.Context, limit int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getRecentTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationTypesByAddress = `-- name: GetRelationTypesByAddress :many
select distinct case
    when t.sender = lower($1) then 'sender'
    when t.proposer = lower($1) then 'proposer'
    else 'unknown'
end as relation
from transactions t
where lower(t.sender) = lower($1) or lower(t.proposer) = lower($1)
`

func (q *Queries) GetRelationTypesByAddress(ctx context.Context, lower string) ([]string, error) {
	rows, err := q.db.Query(ctx, getRelationTypesByAddress, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var relation string
		if err := rows.Scan(&relation); err != nil {
			return nil, err
		}
		items = append(items, relation)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLANodeReport = `-- name: GetSLANodeReport :one

select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where sla_rollup_id = $1 and validator_address = $2
`

type GetSLANodeReportParams struct {
	SlaRollupID      int32  `json:"sla_rollup_id"`
	ValidatorAddress string `json:"validator_address"`
}

// ========================================
// sla node reports queries
// ========================================
func (q *Queries) GetSLANodeReport(ctx context.Context, arg GetSLANodeReportParams) (SlaNodeReport, error) {
	row := q.db.QueryRow(ctx, getSLANodeReport, arg.SlaRollupID, arg.ValidatorAddress)
	var i SlaNodeReport
	err := row.Scan(
		&i.ID,
		&i.SlaRollupID,
		&i.ValidatorAddress,
		&i.NumBlocksProposed,
		&i.ChallengesReceived,
		&i.ChallengesFailed,
		&i.CreatedAt,
	)
	return i, err
}

const getSLAPerformanceData = `-- name: GetSLAPerformanceData :many
select
    sr.id as rollup_id,
    sr.block_start,
    sr.block_end,
    sr.validator_count,
    sr.block_quota,
    sr.created_at,
    count(distinct snr.validator_address) filter (
        where snr.num_blocks_proposed >= (sr.block_quota * 0.8)
          and (snr.challenges_received = 0 or
               (1.0 - (snr.challenges_failed::float / snr.challenges_received)) >= 0.8)
    ) as healthy_validators
from sla_rollups sr
left join sla_node_reports snr on snr.sla_rollup_id = sr.id
group by sr.id, sr.block_start, sr.block_end, sr.validator_count, sr.block_quota, sr.created_at
order by sr.id desc
limit $1
`

type GetSLAPerformanceDataRow struct {
	RollupID          int32            `json:"rollup_id"`
	BlockStart        int64            `json:"block_start"`
	BlockEnd          int64            `json:"block_end"`
	ValidatorCount    int32            `json:"validator_count"`
	BlockQuota        int32            `json:"block_quota"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	HealthyValidators int64            `json:"healthy_validators"`
}

// Get SLA performance data for charting (last N rollups)
func (q *Queries) GetSLAPerformanceData(ctx context.Context, limit int32) ([]GetSLAPerformanceDataRow, error) {
	rows, err := q.db.Query(ctx, getSLAPerformanceData, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSLAPerformanceDataRow
	for rows.Next() {
		var i GetSLAPerformanceDataRow
		if err := rows.Scan(
			&i.RollupID,
			&i.BlockStart,
			&i.BlockEnd,
			&i.ValidatorCount,
			&i.BlockQuota,
			&i.CreatedAt,
			&i.HealthyValidators,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLARollup = `-- name: GetSLARollup :one

select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups where id = $1
`

// ========================================
// sla rollups queries
// ========================================
func (q *Queries) GetSLARollup(ctx context.Context, id int32) (SlaRollup, error) {
	row := q.db.QueryRow(ctx, getSLARollup, id)
	var i SlaRollup
	err := row.Scan(
		&i.ID,
		&i.BlockStart,
		&i.BlockEnd,
		&i.ValidatorCount,
		&i.BlockQuota,
		&i.TxHash,
		&i.BlockHeight,
		&i.CreatedAt,
	)
	return i, err
}

const getSlaNodeReportsByAddress = `-- name: GetSlaNodeReportsByAddress :many
select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where validator_address = lower($1)
order by sla_rollup_id desc
limit $2
`

type GetSlaNodeReportsByAddressParams struct {
	Lower string `json:"lower"`
	Limit int32  `json:"limit"`
}

func (q *Queries) GetSlaNodeReportsByAddress(ctx context.Context, arg GetSlaNodeReportsByAddressParams) ([]SlaNodeReport, error) {
	rows, err := q.db.Query(ctx, getSlaNodeReportsByAddress, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaNodeReport
	for rows.Next() {
		var i SlaNodeReport
		if err := rows.Scan(
			&i.ID,
			&i.SlaRollupID,
			&i.ValidatorAddress,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlaRollupById = `-- name: GetSlaRollupById :one
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups where id = $1
`

func (q *Queries) GetSlaRollupById(ctx context.Context, id int32) (SlaRollup, error) {
	row := q.db.QueryRow(ctx, getSlaRollupById, id)
	var i SlaRollup
	err := row.Scan(
		&i.ID,
		&i.BlockStart,
		&i.BlockEnd,
		&i.ValidatorCount,
		&i.BlockQuota,
		&i.TxHash,
		&i.BlockHeight,
		&i.CreatedAt,
	)
	return i, err
}

const getSlaRollupByTxHash = `-- name: GetSlaRollupByTxHash :one
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups where tx_hash = $1
`

func (q *Queries) GetSlaRollupByTxHash(ctx context.Context, txHash string) (SlaRollup, error) {
	row := q.db.QueryRow(ctx, getSlaRollupByTxHash, txHash)
	var i SlaRollup
	err := row.Scan(
		&i.ID,
		&i.BlockStart,
		&i.BlockEnd,
		&i.ValidatorCount,
		&i.BlockQuota,
		&i.TxHash,
		&i.BlockHeight,
		&i.CreatedAt,
	)
	return i, err
}

const getSlaRollupsWithPagination = `-- name: GetSlaRollupsWithPagination :many
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups
order by id desc
limit $1 offset $2
`

type GetSlaRollupsWithPaginationParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSlaRollupsWithPagination(ctx context.Context, arg GetSlaRollupsWithPaginationParams) ([]SlaRollup, error) {
	rows, err := q.db.Query(ctx, getSlaRollupsWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaRollup
	for rows.Next() {
		var i SlaRollup
		if err := rows.Scan(
			&i.ID,
			&i.BlockStart,
			&i.BlockEnd,
			&i.ValidatorCount,
			&i.BlockQuota,
			&i.TxHash,
			&i.BlockHeight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageProofByTxHash = `-- name: GetStorageProofByTxHash :one

select id, prover_address, challenge_id, proof_data, block_height, tx_hash, created_at from storage_proofs where tx_hash = $1
`

// ========================================
// storage proofs queries
// ========================================
func (q *Queries) GetStorageProofByTxHash(ctx context.Context, txHash string) (StorageProof, error) {
	row := q.db.QueryRow(ctx, getStorageProofByTxHash, txHash)
	var i StorageProof
	err := row.Scan(
		&i.ID,
		&i.ProverAddress,
		&i.ChallengeID,
		&i.ProofData,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageProofVerificationByTxHash = `-- name: GetStorageProofVerificationByTxHash :one
select id, challenge_id, verifier_address, is_valid, verification_data, block_height, tx_hash, created_at from storage_proof_verifications where tx_hash = $1
`

func (q *Queries) GetStorageProofVerificationByTxHash(ctx context.Context, txHash string) (StorageProofVerification, error) {
	row := q.db.QueryRow(ctx, getStorageProofVerificationByTxHash, txHash)
	var i StorageProofVerification
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.VerifierAddress,
		&i.IsValid,
		&i.VerificationData,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one

select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions where tx_hash = $1
`

// ========================================
// transactions queries
// ========================================
func (q *Queries) GetTransaction(ctx context.Context, txHash string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, txHash)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxHash,
		&i.BlockHeight,
		&i.TxIndex,
		&i.TxType,
		&i.Proposer,
		&i.Sender,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionBreakdown = `-- name: GetTransactionBreakdown :many
select
    tx_type,
    total_count,
    latest_transaction
from transaction_type_stats
order by total_count desc
`

type GetTransactionBreakdownRow struct {
	TxType            string           `json:"tx_type"`
	TotalCount        int64            `json:"total_count"`
	LatestTransaction pgtype.Timestamp `json:"latest_transaction"`
}

// Get transaction type breakdown for dashboard
func (q *Queries) GetTransactionBreakdown(ctx context.Context) ([]GetTransactionBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getTransactionBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionBreakdownRow
	for rows.Next() {
		var i GetTransactionBreakdownRow
		if err := rows.Scan(&i.TxType, &i.TotalCount, &i.LatestTransaction); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByHash = `-- name: GetTransactionByHash :one
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions where tx_hash = $1
`

func (q *Queries) GetTransactionByHash(ctx context.Context, txHash string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByHash, txHash)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TxHash,
		&i.BlockHeight,
		&i.TxIndex,
		&i.TxType,
		&i.Proposer,
		&i.Sender,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionCountByAddress = `-- name: GetTransactionCountByAddress :one
select count(*)
from transactions t
where (lower(t.sender) = lower($1) or lower(t.proposer) = lower($1))
  and ($2 = '' or case
        when t.sender = lower($1) then 'sender'
        when t.proposer = lower($1) then 'proposer'
        else 'unknown'
    end = $2)
  and ($3::timestamp is null or t.created_at >= $3)
  and ($4::timestamp is null or t.created_at <= $4)
`

type GetTransactionCountByAddressParams struct {
	Lower   string           `json:"lower"`
	Column2 interface{}      `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
	Column4 pgtype.Timestamp `json:"column_4"`
}

func (q *Queries) GetTransactionCountByAddress(ctx context.Context, arg GetTransactionCountByAddressParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTransactionCountByAddress,
		arg.Lower,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransactionTypeStat = `-- name: GetTransactionTypeStat :one
select tx_type, total_count, latest_transaction, updated_at from transaction_type_stats
where tx_type = $1
`

func (q *Queries) GetTransactionTypeStat(ctx context.Context, txType string) (TransactionTypeStat, error) {
	row := q.db.QueryRow(ctx, getTransactionTypeStat, txType)
	var i TransactionTypeStat
	err := row.Scan(
		&i.TxType,
		&i.TotalCount,
		&i.LatestTransaction,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionTypeStats = `-- name: GetTransactionTypeStats :many
select tx_type, total_count, latest_transaction, updated_at from transaction_type_stats
order by total_count desc
`

func (q *Queries) GetTransactionTypeStats(ctx context.Context) ([]TransactionTypeStat, error) {
	rows, err := q.db.Query(ctx, getTransactionTypeStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionTypeStat
	for rows.Next() {
		var i TransactionTypeStat
		if err := rows.Scan(
			&i.TxType,
			&i.TotalCount,
			&i.LatestTransaction,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionWindowCounts = `-- name: GetTransactionWindowCounts :one
select get_transaction_window_counts from get_transaction_window_counts()
`

func (q *Queries) GetTransactionWindowCounts(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTransactionWindowCounts)
	var get_transaction_window_counts interface{}
	err := row.Scan(&get_transaction_window_counts)
	return get_transaction_window_counts, err
}

const getTransactionsByAddress = `-- name: GetTransactionsByAddress :many
select
    t.id,
    t.tx_hash,
    t.block_height,
    t.tx_index,
    t.tx_type,
    t.created_at,
    case
        when t.sender = lower($1) then 'sender'
        when t.proposer = lower($1) then 'proposer'
        else 'unknown'
    end as relation
from transactions t
where (lower(t.sender) = lower($1) or lower(t.proposer) = lower($1))
  and ($2 = '' or case
        when t.sender = lower($1) then 'sender'
        when t.proposer = lower($1) then 'proposer'
        else 'unknown'
    end = $2)
  and ($3::timestamp is null or t.created_at >= $3)
  and ($4::timestamp is null or t.created_at <= $4)
order by t.created_at desc
limit $5 offset $6
`

type GetTransactionsByAddressParams struct {
	Lower   string           `json:"lower"`
	Column2 interface{}      `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
	Column4 pgtype.Timestamp `json:"column_4"`
	Limit   int32            `json:"limit"`
	Offset  int32            `json:"offset"`
}

type GetTransactionsByAddressRow struct {
	ID          pgtype.Int4      `json:"id"`
	TxHash      string           `json:"tx_hash"`
	BlockHeight int64            `json:"block_height"`
	TxIndex     int32            `json:"tx_index"`
	TxType      string           `json:"tx_type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Relation    string           `json:"relation"`
}

// Get transactions for an address with optional filters
func (q *Queries) GetTransactionsByAddress(ctx context.Context, arg GetTransactionsByAddressParams) ([]GetTransactionsByAddressRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByAddress,
		arg.Lower,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByAddressRow
	for rows.Next() {
		var i GetTransactionsByAddressRow
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.CreatedAt,
			&i.Relation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByBlock = `-- name: GetTransactionsByBlock :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where block_height = $1
order by tx_index asc
`

func (q *Queries) GetTransactionsByBlock(ctx context.Context, blockHeight int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByBlock, blockHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByPage = `-- name: GetTransactionsByPage :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
order by created_at desc
limit $1 offset $2
`

type GetTransactionsByPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetTransactionsByPage(ctx context.Context, arg GetTransactionsByPageParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByProposer = `-- name: GetTransactionsByProposer :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where proposer = $1
order by created_at desc
limit $2 offset $3
`

type GetTransactionsByProposerParams struct {
	Proposer string `json:"proposer"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetTransactionsByProposer(ctx context.Context, arg GetTransactionsByProposerParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByProposer, arg.Proposer, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsBySender = `-- name: GetTransactionsBySender :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where sender = $1
order by created_at desc
limit $2 offset $3
`

type GetTransactionsBySenderParams struct {
	Sender string `json:"sender"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetTransactionsBySender(ctx context.Context, arg GetTransactionsBySenderParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsBySender, arg.Sender, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByType = `-- name: GetTransactionsByType :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where tx_type = $1
order by created_at desc
limit $2 offset $3
`

type GetTransactionsByTypeParams struct {
	TxType string `json:"tx_type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetTransactionsByType(ctx context.Context, arg GetTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByType, arg.TxType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByTypeAndBlock = `-- name: GetTransactionsByTypeAndBlock :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where tx_type = $1
and block_height = $2
order by tx_index asc
`

type GetTransactionsByTypeAndBlockParams struct {
	TxType      string `json:"tx_type"`
	BlockHeight int64  `json:"block_height"`
}

func (q *Queries) GetTransactionsByTypeAndBlock(ctx context.Context, arg GetTransactionsByTypeAndBlockParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByTypeAndBlock, arg.TxType, arg.BlockHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByTypeAndBlockRange = `-- name: GetTransactionsByTypeAndBlockRange :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where tx_type = $1
and block_height >= $2
and block_height <= $3
order by block_height, tx_index
`

type GetTransactionsByTypeAndBlockRangeParams struct {
	TxType        string `json:"tx_type"`
	BlockHeight   int64  `json:"block_height"`
	BlockHeight_2 int64  `json:"block_height_2"`
}

func (q *Queries) GetTransactionsByTypeAndBlockRange(ctx context.Context, arg GetTransactionsByTypeAndBlockRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByTypeAndBlockRange, arg.TxType, arg.BlockHeight, arg.BlockHeight_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidator = `-- name: GetValidator :one

select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators where address = $1
`

// ========================================
// validators queries
// ========================================
func (q *Queries) GetValidator(ctx context.Context, address string) (Validator, error) {
	row := q.db.QueryRow(ctx, getValidator, address)
	var i Validator
	err := row.Scan(
		&i.Address,
		&i.CometAddress,
		&i.Endpoint,
		&i.NodeType,
		&i.Spid,
		&i.VotingPower,
		&i.Status,
		&i.RegisteredAt,
		&i.DeregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidatorByAddress = `-- name: GetValidatorByAddress :one
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators where address = $1
`

func (q *Queries) GetValidatorByAddress(ctx context.Context, address string) (Validator, error) {
	row := q.db.QueryRow(ctx, getValidatorByAddress, address)
	var i Validator
	err := row.Scan(
		&i.Address,
		&i.CometAddress,
		&i.Endpoint,
		&i.NodeType,
		&i.Spid,
		&i.VotingPower,
		&i.Status,
		&i.RegisteredAt,
		&i.DeregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidatorByCometAddress = `-- name: GetValidatorByCometAddress :one
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators where comet_address = $1
`

func (q *Queries) GetValidatorByCometAddress(ctx context.Context, cometAddress string) (Validator, error) {
	row := q.db.QueryRow(ctx, getValidatorByCometAddress, cometAddress)
	var i Validator
	err := row.Scan(
		&i.Address,
		&i.CometAddress,
		&i.Endpoint,
		&i.NodeType,
		&i.Spid,
		&i.VotingPower,
		&i.Status,
		&i.RegisteredAt,
		&i.DeregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidatorDeregistrationByTxHash = `-- name: GetValidatorDeregistrationByTxHash :one
select id, validator_address, event_type, block_height, tx_hash, created_at from validator_events
where tx_hash = $1 and event_type = 'deregistration'
limit 1
`

func (q *Queries) GetValidatorDeregistrationByTxHash(ctx context.Context, txHash string) (ValidatorEvent, error) {
	row := q.db.QueryRow(ctx, getValidatorDeregistrationByTxHash, txHash)
	var i ValidatorEvent
	err := row.Scan(
		&i.ID,
		&i.ValidatorAddress,
		&i.EventType,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getValidatorDeregistrations = `-- name: GetValidatorDeregistrations :many
select
    ve.id,
    ve.validator_address as comet_address,
    ve.block_height,
    ve.tx_hash,
    ve.created_at,
    v.address,
    v.endpoint,
    v.node_type,
    v.spid,
    v.voting_power
from validator_events ve
left join validators v on v.address = ve.validator_address
where ve.event_type = 'deregistration'
order by ve.created_at desc
limit $1 offset $2
`

type GetValidatorDeregistrationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetValidatorDeregistrationsRow struct {
	ID           int32            `json:"id"`
	CometAddress string           `json:"comet_address"`
	BlockHeight  int64            `json:"block_height"`
	TxHash       string           `json:"tx_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Address      pgtype.Text      `json:"address"`
	Endpoint     pgtype.Text      `json:"endpoint"`
	NodeType     pgtype.Text      `json:"node_type"`
	Spid         pgtype.Text      `json:"spid"`
	VotingPower  pgtype.Int8      `json:"voting_power"`
}

func (q *Queries) GetValidatorDeregistrations(ctx context.Context, arg GetValidatorDeregistrationsParams) ([]GetValidatorDeregistrationsRow, error) {
	rows, err := q.db.Query(ctx, getValidatorDeregistrations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValidatorDeregistrationsRow
	for rows.Next() {
		var i GetValidatorDeregistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CometAddress,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
			&i.Address,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorEvents = `-- name: GetValidatorEvents :many

select id, validator_address, event_type, block_height, tx_hash, created_at from validator_events
where validator_address = $1
order by created_at desc
limit $2
`

type GetValidatorEventsParams struct {
	ValidatorAddress string `json:"validator_address"`
	Limit            int32  `json:"limit"`
}

// ========================================
// validator events queries
// ========================================
func (q *Queries) GetValidatorEvents(ctx context.Context, arg GetValidatorEventsParams) ([]ValidatorEvent, error) {
	rows, err := q.db.Query(ctx, getValidatorEvents, arg.ValidatorAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidatorEvent
	for rows.Next() {
		var i ValidatorEvent
		if err := rows.Scan(
			&i.ID,
			&i.ValidatorAddress,
			&i.EventType,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorEventsByType = `-- name: GetValidatorEventsByType :many
select id, validator_address, event_type, block_height, tx_hash, created_at from validator_events
where validator_address = $1 and event_type = $2
order by created_at desc
limit $3
`

type GetValidatorEventsByTypeParams struct {
	ValidatorAddress string `json:"validator_address"`
	EventType        string `json:"event_type"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) GetValidatorEventsByType(ctx context.Context, arg GetValidatorEventsByTypeParams) ([]ValidatorEvent, error) {
	rows, err := q.db.Query(ctx, getValidatorEventsByType, arg.ValidatorAddress, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidatorEvent
	for rows.Next() {
		var i ValidatorEvent
		if err := rows.Scan(
			&i.ID,
			&i.ValidatorAddress,
			&i.EventType,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorRegistrationByTxHash = `-- name: GetValidatorRegistrationByTxHash :one
select id, validator_address, event_type, block_height, tx_hash, created_at from validator_events
where tx_hash = $1 and event_type = 'registration'
limit 1
`

func (q *Queries) GetValidatorRegistrationByTxHash(ctx context.Context, txHash string) (ValidatorEvent, error) {
	row := q.db.QueryRow(ctx, getValidatorRegistrationByTxHash, txHash)
	var i ValidatorEvent
	err := row.Scan(
		&i.ID,
		&i.ValidatorAddress,
		&i.EventType,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getValidatorRegistrations = `-- name: GetValidatorRegistrations :many
select
    ve.id,
    ve.validator_address,
    ve.block_height,
    ve.tx_hash,
    ve.created_at,
    v.address,
    v.endpoint,
    v.comet_address,
    v.node_type,
    v.spid,
    v.voting_power
from validator_events ve
join validators v on v.address = ve.validator_address
where ve.event_type = 'registration'
order by ve.created_at desc
limit $1 offset $2
`

type GetValidatorRegistrationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetValidatorRegistrationsRow struct {
	ID               int32            `json:"id"`
	ValidatorAddress string           `json:"validator_address"`
	BlockHeight      int64            `json:"block_height"`
	TxHash           string           `json:"tx_hash"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	Address          string           `json:"address"`
	Endpoint         string           `json:"endpoint"`
	CometAddress     string           `json:"comet_address"`
	NodeType         string           `json:"node_type"`
	Spid             string           `json:"spid"`
	VotingPower      int64            `json:"voting_power"`
}

func (q *Queries) GetValidatorRegistrations(ctx context.Context, arg GetValidatorRegistrationsParams) ([]GetValidatorRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, getValidatorRegistrations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValidatorRegistrationsRow
	for rows.Next() {
		var i GetValidatorRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ValidatorAddress,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
			&i.Address,
			&i.Endpoint,
			&i.CometAddress,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorStats = `-- name: GetValidatorStats :one
select validator_address, total_blocks_proposed, total_sla_rollups, sla_rollups_passed, sla_rollups_failed, last_block_proposed_height, last_sla_rollup_id, updated_at from validator_stats where validator_address = $1
`

func (q *Queries) GetValidatorStats(ctx context.Context, validatorAddress string) (ValidatorStat, error) {
	row := q.db.QueryRow(ctx, getValidatorStats, validatorAddress)
	var i ValidatorStat
	err := row.Scan(
		&i.ValidatorAddress,
		&i.TotalBlocksProposed,
		&i.TotalSlaRollups,
		&i.SlaRollupsPassed,
		&i.SlaRollupsFailed,
		&i.LastBlockProposedHeight,
		&i.LastSlaRollupID,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidatorUptimeMap = `-- name: GetValidatorUptimeMap :many
select
    validator_address,
    sla_rollup_id,
    num_blocks_proposed,
    challenges_received,
    challenges_failed,
    created_at
from sla_node_reports
where validator_address = any($1::text[])
  and sla_rollup_id in (
    select id from sla_rollups order by id desc limit $2
  )
order by validator_address, sla_rollup_id desc
`

type GetValidatorUptimeMapParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
}

type GetValidatorUptimeMapRow struct {
	ValidatorAddress   string           `json:"validator_address"`
	SlaRollupID        int32            `json:"sla_rollup_id"`
	NumBlocksProposed  int32            `json:"num_blocks_proposed"`
	ChallengesReceived int32            `json:"challenges_received"`
	ChallengesFailed   int32            `json:"challenges_failed"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

// Get last N SLA rollups for multiple validators
func (q *Queries) GetValidatorUptimeMap(ctx context.Context, arg GetValidatorUptimeMapParams) ([]GetValidatorUptimeMapRow, error) {
	rows, err := q.db.Query(ctx, getValidatorUptimeMap, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValidatorUptimeMapRow
	for rows.Next() {
		var i GetValidatorUptimeMapRow
		if err := rows.Scan(
			&i.ValidatorAddress,
			&i.SlaRollupID,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorsForSlaRollup = `-- name: GetValidatorsForSlaRollup :many
select
    v.address, v.comet_address, v.endpoint, v.node_type, v.spid, v.voting_power, v.status, v.registered_at, v.deregistered_at, v.created_at, v.updated_at,
    snr.num_blocks_proposed
from validators v
left join sla_node_reports snr on snr.validator_address = v.comet_address and snr.sla_rollup_id = $1
where v.status = 'active'
order by v.voting_power desc
`

type GetValidatorsForSlaRollupRow struct {
	Address           string           `json:"address"`
	CometAddress      string           `json:"comet_address"`
	Endpoint          string           `json:"endpoint"`
	NodeType          string           `json:"node_type"`
	Spid              string           `json:"spid"`
	VotingPower       int64            `json:"voting_power"`
	Status            string           `json:"status"`
	RegisteredAt      int64            `json:"registered_at"`
	DeregisteredAt    pgtype.Int8      `json:"deregistered_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	NumBlocksProposed pgtype.Int4      `json:"num_blocks_proposed"`
}

func (q *Queries) GetValidatorsForSlaRollup(ctx context.Context, slaRollupID int32) ([]GetValidatorsForSlaRollupRow, error) {
	rows, err := q.db.Query(ctx, getValidatorsForSlaRollup, slaRollupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValidatorsForSlaRollupRow
	for rows.Next() {
		var i GetValidatorsForSlaRollupRow
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NumBlocksProposed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorsWithRecentUptime = `-- name: GetValidatorsWithRecentUptime :many

select
    v.address,
    v.comet_address,
    v.endpoint,
    v.node_type,
    v.spid,
    v.voting_power,
    v.status,
    v.registered_at,
    v.created_at,
    v.updated_at
from validators v
where ($1::text is null or v.status = $1)
order by v.voting_power desc
limit $2 offset $3
`

type GetValidatorsWithRecentUptimeParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetValidatorsWithRecentUptimeRow struct {
	Address      string           `json:"address"`
	CometAddress string           `json:"comet_address"`
	Endpoint     string           `json:"endpoint"`
	NodeType     string           `json:"node_type"`
	Spid         string           `json:"spid"`
	VotingPower  int64            `json:"voting_power"`
	Status       string           `json:"status"`
	RegisteredAt int64            `json:"registered_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// ========================================
// validators uptime page queries
// ========================================
// Get all validators with their recent SLA rollup performance
func (q *Queries) GetValidatorsWithRecentUptime(ctx context.Context, arg GetValidatorsWithRecentUptimeParams) ([]GetValidatorsWithRecentUptimeRow, error) {
	rows, err := q.db.Query(ctx, getValidatorsWithRecentUptime, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValidatorsWithRecentUptimeRow
	for rows.Next() {
		var i GetValidatorsWithRecentUptimeRow
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
select address, user_id from accounts
limit $1 offset $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.Address, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveValidators = `-- name: ListActiveValidators :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
where status = 'active'
order by voting_power desc
limit $1 offset $2
`

type ListActiveValidatorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveValidators(ctx context.Context, arg ListActiveValidatorsParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, listActiveValidators, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many
select height, hash, block_time, proposer_address, data, created_at from blocks
order by height desc
limit $1 offset $2
`

type ListBlocksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBlocks(ctx context.Context, arg ListBlocksParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.BlockTime,
			&i.ProposerAddress,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManageEntities = `-- name: ListManageEntities :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
order by created_at desc
limit $1 offset $2
`

type ListManageEntitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListManageEntities(ctx context.Context, arg ListManageEntitiesParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, listManageEntities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlays = `-- name: ListPlays :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
order by played_at desc
limit $1 offset $2
`

type ListPlaysParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlays(ctx context.Context, arg ListPlaysParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, listPlays, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLANodeReportsByRollup = `-- name: ListSLANodeReportsByRollup :many
select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where sla_rollup_id = $1
order by num_blocks_proposed desc
`

func (q *Queries) ListSLANodeReportsByRollup(ctx context.Context, slaRollupID int32) ([]SlaNodeReport, error) {
	rows, err := q.db.Query(ctx, listSLANodeReportsByRollup, slaRollupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaNodeReport
	for rows.Next() {
		var i SlaNodeReport
		if err := rows.Scan(
			&i.ID,
			&i.SlaRollupID,
			&i.ValidatorAddress,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLANodeReportsByValidator = `-- name: ListSLANodeReportsByValidator :many
select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where validator_address = $1
order by sla_rollup_id desc
limit $2
`

type ListSLANodeReportsByValidatorParams struct {
	ValidatorAddress string `json:"validator_address"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) ListSLANodeReportsByValidator(ctx context.Context, arg ListSLANodeReportsByValidatorParams) ([]SlaNodeReport, error) {
	rows, err := q.db.Query(ctx, listSLANodeReportsByValidator, arg.ValidatorAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaNodeReport
	for rows.Next() {
		var i SlaNodeReport
		if err := rows.Scan(
			&i.ID,
			&i.SlaRollupID,
			&i.ValidatorAddress,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLARollups = `-- name: ListSLARollups :many
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups
order by id desc
limit $1 offset $2
`

type ListSLARollupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSLARollups(ctx context.Context, arg ListSLARollupsParams) ([]SlaRollup, error) {
	rows, err := q.db.Query(ctx, listSLARollups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaRollup
	for rows.Next() {
		var i SlaRollup
		if err := rows.Scan(
			&i.ID,
			&i.BlockStart,
			&i.BlockEnd,
			&i.ValidatorCount,
			&i.BlockQuota,
			&i.TxHash,
			&i.BlockHeight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
select id, tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
order by created_at desc
limit $1 offset $2
`

type ListTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidators = `-- name: ListValidators :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
order by voting_power desc
limit $1 offset $2
`

type ListValidatorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListValidators(ctx context.Context, arg ListValidatorsParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, listValidators, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidatorsByStatus = `-- name: ListValidatorsByStatus :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
where status = $1
order by voting_power desc
limit $2 offset $3
`

type ListValidatorsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListValidatorsByStatus(ctx context.Context, arg ListValidatorsByStatusParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, listValidatorsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
