// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlocks = `-- name: CountBlocks :one
select count(*) from blocks
`

func (q *Queries) CountBlocks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlocks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSLARollups = `-- name: CountSLARollups :one
select count(*) from sla_rollups
`

func (q *Queries) CountSLARollups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSLARollups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactions = `-- name: CountTransactions :one
select count(*) from transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByBlock = `-- name: CountTransactionsByBlock :one
select count(*) from transactions
where block_height = $1
`

func (q *Queries) CountTransactionsByBlock(ctx context.Context, blockHeight int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByBlock, blockHeight)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidators = `-- name: CountValidators :one
select count(*) from validators
`

func (q *Queries) CountValidators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countValidators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidatorsByStatus = `-- name: CountValidatorsByStatus :one
select count(*) from validators where status = $1
`

func (q *Queries) CountValidatorsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countValidatorsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filterValidatorsByEndpoint = `-- name: FilterValidatorsByEndpoint :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
where endpoint like '%' || $1 || '%'
  and ($2::text is null or status = $2)
order by voting_power desc
limit $3 offset $4
`

type FilterValidatorsByEndpointParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Column2 string      `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) FilterValidatorsByEndpoint(ctx context.Context, arg FilterValidatorsByEndpointParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, filterValidatorsByEndpoint,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccount = `-- name: GetAccount :one

select address, user_id from accounts where address = $1
`

// ========================================
// accounts queries
// ========================================
func (q *Queries) GetAccount(ctx context.Context, address string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, address)
	var i Account
	err := row.Scan(&i.Address, &i.UserID)
	return i, err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
select address, user_id from accounts where user_id = $1
`

func (q *Queries) GetAccountByUserID(ctx context.Context, userID pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserID, userID)
	var i Account
	err := row.Scan(&i.Address, &i.UserID)
	return i, err
}

const getBlock = `-- name: GetBlock :one

select height, hash, block_time, proposer_address, data, created_at from blocks where height = $1
`

// ========================================
// blocks queries
// ========================================
func (q *Queries) GetBlock(ctx context.Context, height int64) (Block, error) {
	row := q.db.QueryRow(ctx, getBlock, height)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.BlockTime,
		&i.ProposerAddress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockByHash = `-- name: GetBlockByHash :one
select height, hash, block_time, proposer_address, data, created_at from blocks where hash = $1
`

func (q *Queries) GetBlockByHash(ctx context.Context, hash string) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockByHash, hash)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.BlockTime,
		&i.ProposerAddress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getChainStats = `-- name: GetChainStats :one
select id, latest_block_height, latest_block_hash, latest_block_time, total_transactions, total_validators, active_validators, avg_block_time_seconds, transactions_24h, transactions_7d, transactions_30d, updated_at from chain_stats where id = 1
`

func (q *Queries) GetChainStats(ctx context.Context) (ChainStat, error) {
	row := q.db.QueryRow(ctx, getChainStats)
	var i ChainStat
	err := row.Scan(
		&i.ID,
		&i.LatestBlockHeight,
		&i.LatestBlockHash,
		&i.LatestBlockTime,
		&i.TotalTransactions,
		&i.TotalValidators,
		&i.ActiveValidators,
		&i.AvgBlockTimeSeconds,
		&i.Transactions24h,
		&i.Transactions7d,
		&i.Transactions30d,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one

select
    cs.latest_block_height,
    cs.latest_block_hash,
    cs.latest_block_time,
    cs.total_transactions,
    cs.total_validators,
    cs.active_validators,
    cs.avg_block_time_seconds,
    cs.transactions_24h,
    cs.transactions_7d,
    cs.transactions_30d,
    (select count(*) from validators where status = 'active') as current_active_validators
from chain_stats cs
where cs.id = 1
`

type GetDashboardStatsRow struct {
	LatestBlockHeight       int64            `json:"latest_block_height"`
	LatestBlockHash         pgtype.Text      `json:"latest_block_hash"`
	LatestBlockTime         pgtype.Timestamp `json:"latest_block_time"`
	TotalTransactions       int64            `json:"total_transactions"`
	TotalValidators         int32            `json:"total_validators"`
	ActiveValidators        int32            `json:"active_validators"`
	AvgBlockTimeSeconds     pgtype.Numeric   `json:"avg_block_time_seconds"`
	Transactions24h         int64            `json:"transactions_24h"`
	Transactions7d          int64            `json:"transactions_7d"`
	Transactions30d         int64            `json:"transactions_30d"`
	CurrentActiveValidators int64            `json:"current_active_validators"`
}

// ========================================
// dashboard queries
// ========================================
// Consolidated query for dashboard statistics
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.LatestBlockHeight,
		&i.LatestBlockHash,
		&i.LatestBlockTime,
		&i.TotalTransactions,
		&i.TotalValidators,
		&i.ActiveValidators,
		&i.AvgBlockTimeSeconds,
		&i.Transactions24h,
		&i.Transactions7d,
		&i.Transactions30d,
		&i.CurrentActiveValidators,
	)
	return i, err
}

const getLatestBlock = `-- name: GetLatestBlock :one
select height, hash, block_time, proposer_address, data, created_at from blocks order by height desc limit 1
`

func (q *Queries) GetLatestBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRow(ctx, getLatestBlock)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.BlockTime,
		&i.ProposerAddress,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSLARollup = `-- name: GetLatestSLARollup :one
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups
order by id desc
limit 1
`

func (q *Queries) GetLatestSLARollup(ctx context.Context) (SlaRollup, error) {
	row := q.db.QueryRow(ctx, getLatestSLARollup)
	var i SlaRollup
	err := row.Scan(
		&i.ID,
		&i.BlockStart,
		&i.BlockEnd,
		&i.ValidatorCount,
		&i.BlockQuota,
		&i.TxHash,
		&i.BlockHeight,
		&i.CreatedAt,
	)
	return i, err
}

const getManageEntitiesByAddress = `-- name: GetManageEntitiesByAddress :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where address = $1
order by created_at desc
limit $2 offset $3
`

type GetManageEntitiesByAddressParams struct {
	Address string `json:"address"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetManageEntitiesByAddress(ctx context.Context, arg GetManageEntitiesByAddressParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByAddress, arg.Address, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntitiesByAddressAndType = `-- name: GetManageEntitiesByAddressAndType :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where address = $1 and entity_type = $2
order by created_at desc
limit $3 offset $4
`

type GetManageEntitiesByAddressAndTypeParams struct {
	Address    string `json:"address"`
	EntityType string `json:"entity_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetManageEntitiesByAddressAndType(ctx context.Context, arg GetManageEntitiesByAddressAndTypeParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByAddressAndType,
		arg.Address,
		arg.EntityType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntitiesByEntity = `-- name: GetManageEntitiesByEntity :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where entity_type = $1 and entity_id = $2
order by created_at desc
limit $3
`

type GetManageEntitiesByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetManageEntitiesByEntity(ctx context.Context, arg GetManageEntitiesByEntityParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntitiesByType = `-- name: GetManageEntitiesByType :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
where entity_type = $1
order by created_at desc
limit $2 offset $3
`

type GetManageEntitiesByTypeParams struct {
	EntityType string `json:"entity_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetManageEntitiesByType(ctx context.Context, arg GetManageEntitiesByTypeParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, getManageEntitiesByType, arg.EntityType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManageEntity = `-- name: GetManageEntity :one

select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities where id = $1
`

// ========================================
// manage entities queries
// ========================================
func (q *Queries) GetManageEntity(ctx context.Context, id int32) (ManageEntity, error) {
	row := q.db.QueryRow(ctx, getManageEntity, id)
	var i ManageEntity
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Metadata,
		&i.Signature,
		&i.Signer,
		&i.Nonce,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPlay = `-- name: GetPlay :one

select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays where id = $1
`

// ========================================
// plays queries
// ========================================
func (q *Queries) GetPlay(ctx context.Context, id int32) (Play, error) {
	row := q.db.QueryRow(ctx, getPlay, id)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.City,
		&i.Region,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.PlayedAt,
		&i.ListenedAt,
		&i.RecordedAt,
		&i.BlockHeight,
		&i.TxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaysByCountry = `-- name: GetPlaysByCountry :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
where country = $1
order by played_at desc
limit $2 offset $3
`

type GetPlaysByCountryParams struct {
	Country string `json:"country"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetPlaysByCountry(ctx context.Context, arg GetPlaysByCountryParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, getPlaysByCountry, arg.Country, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaysByTrack = `-- name: GetPlaysByTrack :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
where track_id = $1
order by played_at desc
limit $2 offset $3
`

type GetPlaysByTrackParams struct {
	TrackID string `json:"track_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetPlaysByTrack(ctx context.Context, arg GetPlaysByTrackParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, getPlaysByTrack, arg.TrackID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaysByUser = `-- name: GetPlaysByUser :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
where user_id = $1
order by played_at desc
limit $2 offset $3
`

type GetPlaysByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetPlaysByUser(ctx context.Context, arg GetPlaysByUserParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, getPlaysByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentBlocks = `-- name: GetRecentBlocks :many
select height, hash, block_time, proposer_address, data, created_at from blocks
order by height desc
limit $1
`

func (q *Queries) GetRecentBlocks(ctx context.Context, limit int32) ([]Block, error) {
	rows, err := q.db.Query(ctx, getRecentBlocks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.BlockTime,
			&i.ProposerAddress,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPlays = `-- name: GetRecentPlays :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
order by played_at desc
limit $1
`

func (q *Queries) GetRecentPlays(ctx context.Context, limit int32) ([]Play, error) {
	rows, err := q.db.Query(ctx, getRecentPlays, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSLANodeReportsForValidator = `-- name: GetRecentSLANodeReportsForValidator :many
select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where validator_address = $1
order by sla_rollup_id desc
limit $2
`

type GetRecentSLANodeReportsForValidatorParams struct {
	ValidatorAddress string `json:"validator_address"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) GetRecentSLANodeReportsForValidator(ctx context.Context, arg GetRecentSLANodeReportsForValidatorParams) ([]SlaNodeReport, error) {
	rows, err := q.db.Query(ctx, getRecentSLANodeReportsForValidator, arg.ValidatorAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaNodeReport
	for rows.Next() {
		var i SlaNodeReport
		if err := rows.Scan(
			&i.ID,
			&i.SlaRollupID,
			&i.ValidatorAddress,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSLARollups = `-- name: GetRecentSLARollups :many
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups
order by id desc
limit $1
`

func (q *Queries) GetRecentSLARollups(ctx context.Context, limit int32) ([]SlaRollup, error) {
	rows, err := q.db.Query(ctx, getRecentSLARollups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaRollup
	for rows.Next() {
		var i SlaRollup
		if err := rows.Scan(
			&i.ID,
			&i.BlockStart,
			&i.BlockEnd,
			&i.ValidatorCount,
			&i.BlockQuota,
			&i.TxHash,
			&i.BlockHeight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTransactions = `-- name: GetRecentTransactions :many
select tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
order by created_at desc
limit $1
`

func (q *Queries) GetRecentTransactions(ctx context.Context, limit int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getRecentTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLANodeReport = `-- name: GetSLANodeReport :one

select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where sla_rollup_id = $1 and validator_address = $2
`

type GetSLANodeReportParams struct {
	SlaRollupID      int32  `json:"sla_rollup_id"`
	ValidatorAddress string `json:"validator_address"`
}

// ========================================
// sla node reports queries
// ========================================
func (q *Queries) GetSLANodeReport(ctx context.Context, arg GetSLANodeReportParams) (SlaNodeReport, error) {
	row := q.db.QueryRow(ctx, getSLANodeReport, arg.SlaRollupID, arg.ValidatorAddress)
	var i SlaNodeReport
	err := row.Scan(
		&i.ID,
		&i.SlaRollupID,
		&i.ValidatorAddress,
		&i.NumBlocksProposed,
		&i.ChallengesReceived,
		&i.ChallengesFailed,
		&i.CreatedAt,
	)
	return i, err
}

const getSLAPerformanceData = `-- name: GetSLAPerformanceData :many
select
    sr.id as rollup_id,
    sr.block_start,
    sr.block_end,
    sr.validator_count,
    sr.block_quota,
    sr.created_at,
    count(distinct snr.validator_address) filter (
        where snr.num_blocks_proposed >= (sr.block_quota * 0.8)
          and (snr.challenges_received = 0 or
               (1.0 - (snr.challenges_failed::float / snr.challenges_received)) >= 0.8)
    ) as healthy_validators
from sla_rollups sr
left join sla_node_reports snr on snr.sla_rollup_id = sr.id
group by sr.id, sr.block_start, sr.block_end, sr.validator_count, sr.block_quota, sr.created_at
order by sr.id desc
limit $1
`

type GetSLAPerformanceDataRow struct {
	RollupID          int32            `json:"rollup_id"`
	BlockStart        int64            `json:"block_start"`
	BlockEnd          int64            `json:"block_end"`
	ValidatorCount    int32            `json:"validator_count"`
	BlockQuota        int32            `json:"block_quota"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	HealthyValidators int64            `json:"healthy_validators"`
}

// Get SLA performance data for charting (last N rollups)
func (q *Queries) GetSLAPerformanceData(ctx context.Context, limit int32) ([]GetSLAPerformanceDataRow, error) {
	rows, err := q.db.Query(ctx, getSLAPerformanceData, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSLAPerformanceDataRow
	for rows.Next() {
		var i GetSLAPerformanceDataRow
		if err := rows.Scan(
			&i.RollupID,
			&i.BlockStart,
			&i.BlockEnd,
			&i.ValidatorCount,
			&i.BlockQuota,
			&i.CreatedAt,
			&i.HealthyValidators,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLARollup = `-- name: GetSLARollup :one

select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups where id = $1
`

// ========================================
// sla rollups queries
// ========================================
func (q *Queries) GetSLARollup(ctx context.Context, id int32) (SlaRollup, error) {
	row := q.db.QueryRow(ctx, getSLARollup, id)
	var i SlaRollup
	err := row.Scan(
		&i.ID,
		&i.BlockStart,
		&i.BlockEnd,
		&i.ValidatorCount,
		&i.BlockQuota,
		&i.TxHash,
		&i.BlockHeight,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one

select tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions where tx_hash = $1
`

// ========================================
// transactions queries
// ========================================
func (q *Queries) GetTransaction(ctx context.Context, txHash string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, txHash)
	var i Transaction
	err := row.Scan(
		&i.TxHash,
		&i.BlockHeight,
		&i.TxIndex,
		&i.TxType,
		&i.Proposer,
		&i.Sender,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionBreakdown = `-- name: GetTransactionBreakdown :many
select
    tx_type,
    total_count,
    latest_transaction
from transaction_type_stats
order by total_count desc
`

type GetTransactionBreakdownRow struct {
	TxType            string           `json:"tx_type"`
	TotalCount        int64            `json:"total_count"`
	LatestTransaction pgtype.Timestamp `json:"latest_transaction"`
}

// Get transaction type breakdown for dashboard
func (q *Queries) GetTransactionBreakdown(ctx context.Context) ([]GetTransactionBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getTransactionBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionBreakdownRow
	for rows.Next() {
		var i GetTransactionBreakdownRow
		if err := rows.Scan(&i.TxType, &i.TotalCount, &i.LatestTransaction); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionTypeStat = `-- name: GetTransactionTypeStat :one
select tx_type, total_count, latest_transaction, updated_at from transaction_type_stats
where tx_type = $1
`

func (q *Queries) GetTransactionTypeStat(ctx context.Context, txType string) (TransactionTypeStat, error) {
	row := q.db.QueryRow(ctx, getTransactionTypeStat, txType)
	var i TransactionTypeStat
	err := row.Scan(
		&i.TxType,
		&i.TotalCount,
		&i.LatestTransaction,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionTypeStats = `-- name: GetTransactionTypeStats :many
select tx_type, total_count, latest_transaction, updated_at from transaction_type_stats
order by total_count desc
`

func (q *Queries) GetTransactionTypeStats(ctx context.Context) ([]TransactionTypeStat, error) {
	rows, err := q.db.Query(ctx, getTransactionTypeStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionTypeStat
	for rows.Next() {
		var i TransactionTypeStat
		if err := rows.Scan(
			&i.TxType,
			&i.TotalCount,
			&i.LatestTransaction,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionWindowCounts = `-- name: GetTransactionWindowCounts :one
select get_transaction_window_counts from get_transaction_window_counts()
`

func (q *Queries) GetTransactionWindowCounts(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTransactionWindowCounts)
	var get_transaction_window_counts interface{}
	err := row.Scan(&get_transaction_window_counts)
	return get_transaction_window_counts, err
}

const getTransactionsByBlock = `-- name: GetTransactionsByBlock :many
select tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where block_height = $1
order by tx_index asc
`

func (q *Queries) GetTransactionsByBlock(ctx context.Context, blockHeight int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByBlock, blockHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByProposer = `-- name: GetTransactionsByProposer :many
select tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where proposer = $1
order by created_at desc
limit $2 offset $3
`

type GetTransactionsByProposerParams struct {
	Proposer string `json:"proposer"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetTransactionsByProposer(ctx context.Context, arg GetTransactionsByProposerParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByProposer, arg.Proposer, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsBySender = `-- name: GetTransactionsBySender :many
select tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where sender = $1
order by created_at desc
limit $2 offset $3
`

type GetTransactionsBySenderParams struct {
	Sender string `json:"sender"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetTransactionsBySender(ctx context.Context, arg GetTransactionsBySenderParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsBySender, arg.Sender, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByType = `-- name: GetTransactionsByType :many
select tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
where tx_type = $1
order by created_at desc
limit $2 offset $3
`

type GetTransactionsByTypeParams struct {
	TxType string `json:"tx_type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetTransactionsByType(ctx context.Context, arg GetTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByType, arg.TxType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidator = `-- name: GetValidator :one

select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators where address = $1
`

// ========================================
// validators queries
// ========================================
func (q *Queries) GetValidator(ctx context.Context, address string) (Validator, error) {
	row := q.db.QueryRow(ctx, getValidator, address)
	var i Validator
	err := row.Scan(
		&i.Address,
		&i.CometAddress,
		&i.Endpoint,
		&i.NodeType,
		&i.Spid,
		&i.VotingPower,
		&i.Status,
		&i.RegisteredAt,
		&i.DeregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidatorByCometAddress = `-- name: GetValidatorByCometAddress :one
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators where comet_address = $1
`

func (q *Queries) GetValidatorByCometAddress(ctx context.Context, cometAddress string) (Validator, error) {
	row := q.db.QueryRow(ctx, getValidatorByCometAddress, cometAddress)
	var i Validator
	err := row.Scan(
		&i.Address,
		&i.CometAddress,
		&i.Endpoint,
		&i.NodeType,
		&i.Spid,
		&i.VotingPower,
		&i.Status,
		&i.RegisteredAt,
		&i.DeregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidatorEvents = `-- name: GetValidatorEvents :many

select id, validator_address, event_type, block_height, tx_hash, created_at from validator_events
where validator_address = $1
order by created_at desc
limit $2
`

type GetValidatorEventsParams struct {
	ValidatorAddress string `json:"validator_address"`
	Limit            int32  `json:"limit"`
}

// ========================================
// validator events queries
// ========================================
func (q *Queries) GetValidatorEvents(ctx context.Context, arg GetValidatorEventsParams) ([]ValidatorEvent, error) {
	rows, err := q.db.Query(ctx, getValidatorEvents, arg.ValidatorAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidatorEvent
	for rows.Next() {
		var i ValidatorEvent
		if err := rows.Scan(
			&i.ID,
			&i.ValidatorAddress,
			&i.EventType,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorEventsByType = `-- name: GetValidatorEventsByType :many
select id, validator_address, event_type, block_height, tx_hash, created_at from validator_events
where validator_address = $1 and event_type = $2
order by created_at desc
limit $3
`

type GetValidatorEventsByTypeParams struct {
	ValidatorAddress string `json:"validator_address"`
	EventType        string `json:"event_type"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) GetValidatorEventsByType(ctx context.Context, arg GetValidatorEventsByTypeParams) ([]ValidatorEvent, error) {
	rows, err := q.db.Query(ctx, getValidatorEventsByType, arg.ValidatorAddress, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidatorEvent
	for rows.Next() {
		var i ValidatorEvent
		if err := rows.Scan(
			&i.ID,
			&i.ValidatorAddress,
			&i.EventType,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorStats = `-- name: GetValidatorStats :one
select validator_address, total_blocks_proposed, total_sla_rollups, sla_rollups_passed, sla_rollups_failed, last_block_proposed_height, last_sla_rollup_id, updated_at from validator_stats where validator_address = $1
`

func (q *Queries) GetValidatorStats(ctx context.Context, validatorAddress string) (ValidatorStat, error) {
	row := q.db.QueryRow(ctx, getValidatorStats, validatorAddress)
	var i ValidatorStat
	err := row.Scan(
		&i.ValidatorAddress,
		&i.TotalBlocksProposed,
		&i.TotalSlaRollups,
		&i.SlaRollupsPassed,
		&i.SlaRollupsFailed,
		&i.LastBlockProposedHeight,
		&i.LastSlaRollupID,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidatorUptimeMap = `-- name: GetValidatorUptimeMap :many
select
    validator_address,
    sla_rollup_id,
    num_blocks_proposed,
    challenges_received,
    challenges_failed,
    created_at
from sla_node_reports
where validator_address = any($1::text[])
  and sla_rollup_id in (
    select id from sla_rollups order by id desc limit $2
  )
order by validator_address, sla_rollup_id desc
`

type GetValidatorUptimeMapParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
}

type GetValidatorUptimeMapRow struct {
	ValidatorAddress   string           `json:"validator_address"`
	SlaRollupID        int32            `json:"sla_rollup_id"`
	NumBlocksProposed  int32            `json:"num_blocks_proposed"`
	ChallengesReceived int32            `json:"challenges_received"`
	ChallengesFailed   int32            `json:"challenges_failed"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

// Get last N SLA rollups for multiple validators
func (q *Queries) GetValidatorUptimeMap(ctx context.Context, arg GetValidatorUptimeMapParams) ([]GetValidatorUptimeMapRow, error) {
	rows, err := q.db.Query(ctx, getValidatorUptimeMap, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValidatorUptimeMapRow
	for rows.Next() {
		var i GetValidatorUptimeMapRow
		if err := rows.Scan(
			&i.ValidatorAddress,
			&i.SlaRollupID,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidatorsWithRecentUptime = `-- name: GetValidatorsWithRecentUptime :many

select
    v.address,
    v.comet_address,
    v.endpoint,
    v.node_type,
    v.spid,
    v.voting_power,
    v.status,
    v.registered_at,
    v.created_at,
    v.updated_at
from validators v
where ($1::text is null or v.status = $1)
order by v.voting_power desc
limit $2 offset $3
`

type GetValidatorsWithRecentUptimeParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetValidatorsWithRecentUptimeRow struct {
	Address      string           `json:"address"`
	CometAddress string           `json:"comet_address"`
	Endpoint     string           `json:"endpoint"`
	NodeType     string           `json:"node_type"`
	Spid         string           `json:"spid"`
	VotingPower  int64            `json:"voting_power"`
	Status       string           `json:"status"`
	RegisteredAt int64            `json:"registered_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// ========================================
// validators uptime page queries
// ========================================
// Get all validators with their recent SLA rollup performance
func (q *Queries) GetValidatorsWithRecentUptime(ctx context.Context, arg GetValidatorsWithRecentUptimeParams) ([]GetValidatorsWithRecentUptimeRow, error) {
	rows, err := q.db.Query(ctx, getValidatorsWithRecentUptime, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetValidatorsWithRecentUptimeRow
	for rows.Next() {
		var i GetValidatorsWithRecentUptimeRow
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
select address, user_id from accounts
limit $1 offset $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.Address, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveValidators = `-- name: ListActiveValidators :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
where status = 'active'
order by voting_power desc
limit $1 offset $2
`

type ListActiveValidatorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveValidators(ctx context.Context, arg ListActiveValidatorsParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, listActiveValidators, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many
select height, hash, block_time, proposer_address, data, created_at from blocks
order by height desc
limit $1 offset $2
`

type ListBlocksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBlocks(ctx context.Context, arg ListBlocksParams) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.BlockTime,
			&i.ProposerAddress,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManageEntities = `-- name: ListManageEntities :many
select id, address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash, created_at from manage_entities
order by created_at desc
limit $1 offset $2
`

type ListManageEntitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListManageEntities(ctx context.Context, arg ListManageEntitiesParams) ([]ManageEntity, error) {
	rows, err := q.db.Query(ctx, listManageEntities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManageEntity
	for rows.Next() {
		var i ManageEntity
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Metadata,
			&i.Signature,
			&i.Signer,
			&i.Nonce,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlays = `-- name: ListPlays :many
select id, user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash, created_at from plays
order by played_at desc
limit $1 offset $2
`

type ListPlaysParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlays(ctx context.Context, arg ListPlaysParams) ([]Play, error) {
	rows, err := q.db.Query(ctx, listPlays, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.City,
			&i.Region,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PlayedAt,
			&i.ListenedAt,
			&i.RecordedAt,
			&i.BlockHeight,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLANodeReportsByRollup = `-- name: ListSLANodeReportsByRollup :many
select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where sla_rollup_id = $1
order by num_blocks_proposed desc
`

func (q *Queries) ListSLANodeReportsByRollup(ctx context.Context, slaRollupID int32) ([]SlaNodeReport, error) {
	rows, err := q.db.Query(ctx, listSLANodeReportsByRollup, slaRollupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaNodeReport
	for rows.Next() {
		var i SlaNodeReport
		if err := rows.Scan(
			&i.ID,
			&i.SlaRollupID,
			&i.ValidatorAddress,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLANodeReportsByValidator = `-- name: ListSLANodeReportsByValidator :many
select id, sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed, created_at from sla_node_reports
where validator_address = $1
order by sla_rollup_id desc
limit $2
`

type ListSLANodeReportsByValidatorParams struct {
	ValidatorAddress string `json:"validator_address"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) ListSLANodeReportsByValidator(ctx context.Context, arg ListSLANodeReportsByValidatorParams) ([]SlaNodeReport, error) {
	rows, err := q.db.Query(ctx, listSLANodeReportsByValidator, arg.ValidatorAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaNodeReport
	for rows.Next() {
		var i SlaNodeReport
		if err := rows.Scan(
			&i.ID,
			&i.SlaRollupID,
			&i.ValidatorAddress,
			&i.NumBlocksProposed,
			&i.ChallengesReceived,
			&i.ChallengesFailed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLARollups = `-- name: ListSLARollups :many
select id, block_start, block_end, validator_count, block_quota, tx_hash, block_height, created_at from sla_rollups
order by id desc
limit $1 offset $2
`

type ListSLARollupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSLARollups(ctx context.Context, arg ListSLARollupsParams) ([]SlaRollup, error) {
	rows, err := q.db.Query(ctx, listSLARollups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaRollup
	for rows.Next() {
		var i SlaRollup
		if err := rows.Scan(
			&i.ID,
			&i.BlockStart,
			&i.BlockEnd,
			&i.ValidatorCount,
			&i.BlockQuota,
			&i.TxHash,
			&i.BlockHeight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
select tx_hash, block_height, tx_index, tx_type, proposer, sender, data, created_at from transactions
order by created_at desc
limit $1 offset $2
`

type ListTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.TxType,
			&i.Proposer,
			&i.Sender,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidators = `-- name: ListValidators :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
order by voting_power desc
limit $1 offset $2
`

type ListValidatorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListValidators(ctx context.Context, arg ListValidatorsParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, listValidators, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidatorsByStatus = `-- name: ListValidatorsByStatus :many
select address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at, deregistered_at, created_at, updated_at from validators
where status = $1
order by voting_power desc
limit $2 offset $3
`

type ListValidatorsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListValidatorsByStatus(ctx context.Context, arg ListValidatorsByStatusParams) ([]Validator, error) {
	rows, err := q.db.Query(ctx, listValidatorsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Validator
	for rows.Next() {
		var i Validator
		if err := rows.Scan(
			&i.Address,
			&i.CometAddress,
			&i.Endpoint,
			&i.NodeType,
			&i.Spid,
			&i.VotingPower,
			&i.Status,
			&i.RegisteredAt,
			&i.DeregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
