// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: writes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertPlaysParams struct {
	UserID      string           `json:"user_id"`
	TrackID     string           `json:"track_id"`
	City        string           `json:"city"`
	Region      string           `json:"region"`
	Country     string           `json:"country"`
	Latitude    pgtype.Numeric   `json:"latitude"`
	Longitude   pgtype.Numeric   `json:"longitude"`
	PlayedAt    pgtype.Timestamp `json:"played_at"`
	ListenedAt  pgtype.Timestamp `json:"listened_at"`
	RecordedAt  pgtype.Timestamp `json:"recorded_at"`
	BlockHeight int64            `json:"block_height"`
	TxHash      string           `json:"tx_hash"`
}

type BatchInsertSLANodeReportsParams struct {
	SlaRollupID        int32  `json:"sla_rollup_id"`
	ValidatorAddress   string `json:"validator_address"`
	NumBlocksProposed  int32  `json:"num_blocks_proposed"`
	ChallengesReceived int32  `json:"challenges_received"`
	ChallengesFailed   int32  `json:"challenges_failed"`
}

type BatchInsertTransactionsParams struct {
	TxHash      string `json:"tx_hash"`
	BlockHeight int64  `json:"block_height"`
	TxIndex     int32  `json:"tx_index"`
	TxType      string `json:"tx_type"`
	Proposer    string `json:"proposer"`
	Sender      string `json:"sender"`
	Data        []byte `json:"data"`
}

const cleanupTransactionWindows = `-- name: CleanupTransactionWindows :one
select cleanup_transaction_windows()
`

func (q *Queries) CleanupTransactionWindows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, cleanupTransactionWindows)
	var cleanup_transaction_windows int64
	err := row.Scan(&cleanup_transaction_windows)
	return cleanup_transaction_windows, err
}

const deleteAccount = `-- name: DeleteAccount :exec
delete from accounts where address = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, address string) error {
	_, err := q.db.Exec(ctx, deleteAccount, address)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
delete from blocks where height = $1
`

func (q *Queries) DeleteBlock(ctx context.Context, height int64) error {
	_, err := q.db.Exec(ctx, deleteBlock, height)
	return err
}

const deleteManageEntitiesByBlock = `-- name: DeleteManageEntitiesByBlock :exec
delete from manage_entities where block_height = $1
`

func (q *Queries) DeleteManageEntitiesByBlock(ctx context.Context, blockHeight int64) error {
	_, err := q.db.Exec(ctx, deleteManageEntitiesByBlock, blockHeight)
	return err
}

const deleteManageEntity = `-- name: DeleteManageEntity :exec
delete from manage_entities where id = $1
`

func (q *Queries) DeleteManageEntity(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteManageEntity, id)
	return err
}

const deleteOldTransactionWindows = `-- name: DeleteOldTransactionWindows :exec
delete from transaction_windows
where block_time < (
    select latest_block_time - interval '30 days'
    from chain_stats
    where id = 1
)
`

func (q *Queries) DeleteOldTransactionWindows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldTransactionWindows)
	return err
}

const deletePlay = `-- name: DeletePlay :exec
delete from plays where id = $1
`

func (q *Queries) DeletePlay(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlay, id)
	return err
}

const deletePlaysByBlock = `-- name: DeletePlaysByBlock :exec
delete from plays where block_height = $1
`

func (q *Queries) DeletePlaysByBlock(ctx context.Context, blockHeight int64) error {
	_, err := q.db.Exec(ctx, deletePlaysByBlock, blockHeight)
	return err
}

const deleteSLANodeReportsByRollup = `-- name: DeleteSLANodeReportsByRollup :exec
delete from sla_node_reports where sla_rollup_id = $1
`

func (q *Queries) DeleteSLANodeReportsByRollup(ctx context.Context, slaRollupID int32) error {
	_, err := q.db.Exec(ctx, deleteSLANodeReportsByRollup, slaRollupID)
	return err
}

const deleteSLANodeReportsByValidator = `-- name: DeleteSLANodeReportsByValidator :exec
delete from sla_node_reports where validator_address = $1
`

func (q *Queries) DeleteSLANodeReportsByValidator(ctx context.Context, validatorAddress string) error {
	_, err := q.db.Exec(ctx, deleteSLANodeReportsByValidator, validatorAddress)
	return err
}

const deleteSLARollup = `-- name: DeleteSLARollup :exec
delete from sla_rollups where id = $1
`

func (q *Queries) DeleteSLARollup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSLARollup, id)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
delete from transactions where tx_hash = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, txHash string) error {
	_, err := q.db.Exec(ctx, deleteTransaction, txHash)
	return err
}

const deleteTransactionsByBlock = `-- name: DeleteTransactionsByBlock :exec
delete from transactions where block_height = $1
`

func (q *Queries) DeleteTransactionsByBlock(ctx context.Context, blockHeight int64) error {
	_, err := q.db.Exec(ctx, deleteTransactionsByBlock, blockHeight)
	return err
}

const deleteValidator = `-- name: DeleteValidator :exec
delete from validators where address = $1
`

func (q *Queries) DeleteValidator(ctx context.Context, address string) error {
	_, err := q.db.Exec(ctx, deleteValidator, address)
	return err
}

const deleteValidatorEventsByValidator = `-- name: DeleteValidatorEventsByValidator :exec
delete from validator_events where validator_address = $1
`

func (q *Queries) DeleteValidatorEventsByValidator(ctx context.Context, validatorAddress string) error {
	_, err := q.db.Exec(ctx, deleteValidatorEventsByValidator, validatorAddress)
	return err
}

const incrementTxTypeStats = `-- name: IncrementTxTypeStats :exec
select increment_tx_type_stats($1, $2)
`

type IncrementTxTypeStatsParams struct {
	PTxType    string           `json:"p_tx_type"`
	PTimestamp pgtype.Timestamp `json:"p_timestamp"`
}

func (q *Queries) IncrementTxTypeStats(ctx context.Context, arg IncrementTxTypeStatsParams) error {
	_, err := q.db.Exec(ctx, incrementTxTypeStats, arg.PTxType, arg.PTimestamp)
	return err
}

const insertAccount = `-- name: InsertAccount :exec

insert into accounts (address, user_id)
values ($1, $2)
`

type InsertAccountParams struct {
	Address string      `json:"address"`
	UserID  pgtype.Text `json:"user_id"`
}

// ========================================
// accounts writes
// ========================================
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount, arg.Address, arg.UserID)
	return err
}

const insertBlock = `-- name: InsertBlock :exec

insert into blocks (height, hash, block_time, proposer_address, data)
values ($1, $2, $3, $4, $5)
`

type InsertBlockParams struct {
	Height          int64            `json:"height"`
	Hash            string           `json:"hash"`
	BlockTime       pgtype.Timestamp `json:"block_time"`
	ProposerAddress string           `json:"proposer_address"`
	Data            []byte           `json:"data"`
}

// ========================================
// blocks writes
// ========================================
func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.Height,
		arg.Hash,
		arg.BlockTime,
		arg.ProposerAddress,
		arg.Data,
	)
	return err
}

const insertManageEntity = `-- name: InsertManageEntity :exec

insert into manage_entities (address, entity_type, entity_id, action, metadata, signature, signer, nonce, block_height, tx_hash)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertManageEntityParams struct {
	Address     string `json:"address"`
	EntityType  string `json:"entity_type"`
	EntityID    int64  `json:"entity_id"`
	Action      string `json:"action"`
	Metadata    []byte `json:"metadata"`
	Signature   string `json:"signature"`
	Signer      string `json:"signer"`
	Nonce       string `json:"nonce"`
	BlockHeight int64  `json:"block_height"`
	TxHash      string `json:"tx_hash"`
}

// ========================================
// manage entities writes
// ========================================
func (q *Queries) InsertManageEntity(ctx context.Context, arg InsertManageEntityParams) error {
	_, err := q.db.Exec(ctx, insertManageEntity,
		arg.Address,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Metadata,
		arg.Signature,
		arg.Signer,
		arg.Nonce,
		arg.BlockHeight,
		arg.TxHash,
	)
	return err
}

const insertPlay = `-- name: InsertPlay :exec

insert into plays (user_id, track_id, city, region, country, latitude, longitude, played_at, listened_at, recorded_at, block_height, tx_hash)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertPlayParams struct {
	UserID      string           `json:"user_id"`
	TrackID     string           `json:"track_id"`
	City        string           `json:"city"`
	Region      string           `json:"region"`
	Country     string           `json:"country"`
	Latitude    pgtype.Numeric   `json:"latitude"`
	Longitude   pgtype.Numeric   `json:"longitude"`
	PlayedAt    pgtype.Timestamp `json:"played_at"`
	ListenedAt  pgtype.Timestamp `json:"listened_at"`
	RecordedAt  pgtype.Timestamp `json:"recorded_at"`
	BlockHeight int64            `json:"block_height"`
	TxHash      string           `json:"tx_hash"`
}

// ========================================
// plays writes
// ========================================
func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) error {
	_, err := q.db.Exec(ctx, insertPlay,
		arg.UserID,
		arg.TrackID,
		arg.City,
		arg.Region,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.PlayedAt,
		arg.ListenedAt,
		arg.RecordedAt,
		arg.BlockHeight,
		arg.TxHash,
	)
	return err
}

const insertSLANodeReport = `-- name: InsertSLANodeReport :exec

insert into sla_node_reports (sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed)
values ($1, $2, $3, $4, $5)
`

type InsertSLANodeReportParams struct {
	SlaRollupID        int32  `json:"sla_rollup_id"`
	ValidatorAddress   string `json:"validator_address"`
	NumBlocksProposed  int32  `json:"num_blocks_proposed"`
	ChallengesReceived int32  `json:"challenges_received"`
	ChallengesFailed   int32  `json:"challenges_failed"`
}

// ========================================
// sla node reports writes
// ========================================
func (q *Queries) InsertSLANodeReport(ctx context.Context, arg InsertSLANodeReportParams) error {
	_, err := q.db.Exec(ctx, insertSLANodeReport,
		arg.SlaRollupID,
		arg.ValidatorAddress,
		arg.NumBlocksProposed,
		arg.ChallengesReceived,
		arg.ChallengesFailed,
	)
	return err
}

const insertSLARollup = `-- name: InsertSLARollup :one

insert into sla_rollups (block_start, block_end, validator_count, block_quota, tx_hash, block_height)
values ($1, $2, $3, $4, $5, $6)
returning id
`

type InsertSLARollupParams struct {
	BlockStart     int64  `json:"block_start"`
	BlockEnd       int64  `json:"block_end"`
	ValidatorCount int32  `json:"validator_count"`
	BlockQuota     int32  `json:"block_quota"`
	TxHash         string `json:"tx_hash"`
	BlockHeight    int64  `json:"block_height"`
}

// ========================================
// sla rollups writes
// ========================================
func (q *Queries) InsertSLARollup(ctx context.Context, arg InsertSLARollupParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertSLARollup,
		arg.BlockStart,
		arg.BlockEnd,
		arg.ValidatorCount,
		arg.BlockQuota,
		arg.TxHash,
		arg.BlockHeight,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertTransaction = `-- name: InsertTransaction :exec

insert into transactions (tx_hash, block_height, tx_index, tx_type, proposer, sender, data)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (tx_hash) do nothing
`

type InsertTransactionParams struct {
	TxHash      string `json:"tx_hash"`
	BlockHeight int64  `json:"block_height"`
	TxIndex     int32  `json:"tx_index"`
	TxType      string `json:"tx_type"`
	Proposer    string `json:"proposer"`
	Sender      string `json:"sender"`
	Data        []byte `json:"data"`
}

// ========================================
// transactions writes
// ========================================
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.TxHash,
		arg.BlockHeight,
		arg.TxIndex,
		arg.TxType,
		arg.Proposer,
		arg.Sender,
		arg.Data,
	)
	return err
}

const insertTransactionWindow = `-- name: InsertTransactionWindow :exec

insert into transaction_windows (tx_hash, tx_type, block_time)
values ($1, $2, $3)
on conflict (tx_hash) do nothing
`

type InsertTransactionWindowParams struct {
	TxHash    string           `json:"tx_hash"`
	TxType    string           `json:"tx_type"`
	BlockTime pgtype.Timestamp `json:"block_time"`
}

// ========================================
// transaction windows writes
// ========================================
func (q *Queries) InsertTransactionWindow(ctx context.Context, arg InsertTransactionWindowParams) error {
	_, err := q.db.Exec(ctx, insertTransactionWindow, arg.TxHash, arg.TxType, arg.BlockTime)
	return err
}

const insertValidator = `-- name: InsertValidator :exec

insert into validators (address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertValidatorParams struct {
	Address      string `json:"address"`
	CometAddress string `json:"comet_address"`
	Endpoint     string `json:"endpoint"`
	NodeType     string `json:"node_type"`
	Spid         string `json:"spid"`
	VotingPower  int64  `json:"voting_power"`
	Status       string `json:"status"`
	RegisteredAt int64  `json:"registered_at"`
}

// ========================================
// validators writes
// ========================================
func (q *Queries) InsertValidator(ctx context.Context, arg InsertValidatorParams) error {
	_, err := q.db.Exec(ctx, insertValidator,
		arg.Address,
		arg.CometAddress,
		arg.Endpoint,
		arg.NodeType,
		arg.Spid,
		arg.VotingPower,
		arg.Status,
		arg.RegisteredAt,
	)
	return err
}

const insertValidatorEvent = `-- name: InsertValidatorEvent :exec

insert into validator_events (validator_address, event_type, block_height, tx_hash)
values ($1, $2, $3, $4)
`

type InsertValidatorEventParams struct {
	ValidatorAddress string `json:"validator_address"`
	EventType        string `json:"event_type"`
	BlockHeight      int64  `json:"block_height"`
	TxHash           string `json:"tx_hash"`
}

// ========================================
// validator events writes
// ========================================
func (q *Queries) InsertValidatorEvent(ctx context.Context, arg InsertValidatorEventParams) error {
	_, err := q.db.Exec(ctx, insertValidatorEvent,
		arg.ValidatorAddress,
		arg.EventType,
		arg.BlockHeight,
		arg.TxHash,
	)
	return err
}

const recalculateValidatorCounts = `-- name: RecalculateValidatorCounts :exec
select recalculate_validator_counts()
`

func (q *Queries) RecalculateValidatorCounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recalculateValidatorCounts)
	return err
}

const updateChainStats = `-- name: UpdateChainStats :exec

select update_chain_stats($1, $2, $3, $4)
`

type UpdateChainStatsParams struct {
	PBlockHeight int64            `json:"p_block_height"`
	PBlockHash   string           `json:"p_block_hash"`
	PBlockTime   pgtype.Timestamp `json:"p_block_time"`
	PTxCount     int32            `json:"p_tx_count"`
}

// ========================================
// stats writes (manual updates)
// ========================================
func (q *Queries) UpdateChainStats(ctx context.Context, arg UpdateChainStatsParams) error {
	_, err := q.db.Exec(ctx, updateChainStats,
		arg.PBlockHeight,
		arg.PBlockHash,
		arg.PBlockTime,
		arg.PTxCount,
	)
	return err
}

const updateValidatorStats = `-- name: UpdateValidatorStats :exec
select update_validator_stats($1, $2, $3, $4)
`

type UpdateValidatorStatsParams struct {
	PValidatorAddress string `json:"p_validator_address"`
	PBlocksProposed   int32  `json:"p_blocks_proposed"`
	PSlaRollupID      int32  `json:"p_sla_rollup_id"`
	PPassed           bool   `json:"p_passed"`
}

func (q *Queries) UpdateValidatorStats(ctx context.Context, arg UpdateValidatorStatsParams) error {
	_, err := q.db.Exec(ctx, updateValidatorStats,
		arg.PValidatorAddress,
		arg.PBlocksProposed,
		arg.PSlaRollupID,
		arg.PPassed,
	)
	return err
}

const updateValidatorStatus = `-- name: UpdateValidatorStatus :exec
update validators set
    status = $2,
    deregistered_at = $3,
    updated_at = now()
where address = $1
`

type UpdateValidatorStatusParams struct {
	Address        string      `json:"address"`
	Status         string      `json:"status"`
	DeregisteredAt pgtype.Int8 `json:"deregistered_at"`
}

func (q *Queries) UpdateValidatorStatus(ctx context.Context, arg UpdateValidatorStatusParams) error {
	_, err := q.db.Exec(ctx, updateValidatorStatus, arg.Address, arg.Status, arg.DeregisteredAt)
	return err
}

const updateValidatorVotingPower = `-- name: UpdateValidatorVotingPower :exec
update validators set
    voting_power = $2,
    updated_at = now()
where address = $1
`

type UpdateValidatorVotingPowerParams struct {
	Address     string `json:"address"`
	VotingPower int64  `json:"voting_power"`
}

func (q *Queries) UpdateValidatorVotingPower(ctx context.Context, arg UpdateValidatorVotingPowerParams) error {
	_, err := q.db.Exec(ctx, updateValidatorVotingPower, arg.Address, arg.VotingPower)
	return err
}

const upsertAccount = `-- name: UpsertAccount :exec
insert into accounts (address, user_id)
values ($1, $2)
on conflict (address) do update set
    user_id = excluded.user_id
`

type UpsertAccountParams struct {
	Address string      `json:"address"`
	UserID  pgtype.Text `json:"user_id"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.Exec(ctx, upsertAccount, arg.Address, arg.UserID)
	return err
}

const upsertBlock = `-- name: UpsertBlock :exec
insert into blocks (height, hash, block_time, proposer_address, data)
values ($1, $2, $3, $4, $5)
on conflict (height) do update set
    hash = excluded.hash,
    block_time = excluded.block_time,
    proposer_address = excluded.proposer_address,
    data = excluded.data
`

type UpsertBlockParams struct {
	Height          int64            `json:"height"`
	Hash            string           `json:"hash"`
	BlockTime       pgtype.Timestamp `json:"block_time"`
	ProposerAddress string           `json:"proposer_address"`
	Data            []byte           `json:"data"`
}

func (q *Queries) UpsertBlock(ctx context.Context, arg UpsertBlockParams) error {
	_, err := q.db.Exec(ctx, upsertBlock,
		arg.Height,
		arg.Hash,
		arg.BlockTime,
		arg.ProposerAddress,
		arg.Data,
	)
	return err
}

const upsertSLANodeReport = `-- name: UpsertSLANodeReport :exec
insert into sla_node_reports (sla_rollup_id, validator_address, num_blocks_proposed, challenges_received, challenges_failed)
values ($1, $2, $3, $4, $5)
on conflict (sla_rollup_id, validator_address) do update set
    num_blocks_proposed = excluded.num_blocks_proposed,
    challenges_received = excluded.challenges_received,
    challenges_failed = excluded.challenges_failed,
    created_at = now()
`

type UpsertSLANodeReportParams struct {
	SlaRollupID        int32  `json:"sla_rollup_id"`
	ValidatorAddress   string `json:"validator_address"`
	NumBlocksProposed  int32  `json:"num_blocks_proposed"`
	ChallengesReceived int32  `json:"challenges_received"`
	ChallengesFailed   int32  `json:"challenges_failed"`
}

func (q *Queries) UpsertSLANodeReport(ctx context.Context, arg UpsertSLANodeReportParams) error {
	_, err := q.db.Exec(ctx, upsertSLANodeReport,
		arg.SlaRollupID,
		arg.ValidatorAddress,
		arg.NumBlocksProposed,
		arg.ChallengesReceived,
		arg.ChallengesFailed,
	)
	return err
}

const upsertTransaction = `-- name: UpsertTransaction :exec
insert into transactions (tx_hash, block_height, tx_index, tx_type, proposer, sender, data)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (tx_hash) do update set
    block_height = excluded.block_height,
    tx_index = excluded.tx_index,
    tx_type = excluded.tx_type,
    proposer = excluded.proposer,
    sender = excluded.sender,
    data = excluded.data
`

type UpsertTransactionParams struct {
	TxHash      string `json:"tx_hash"`
	BlockHeight int64  `json:"block_height"`
	TxIndex     int32  `json:"tx_index"`
	TxType      string `json:"tx_type"`
	Proposer    string `json:"proposer"`
	Sender      string `json:"sender"`
	Data        []byte `json:"data"`
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) error {
	_, err := q.db.Exec(ctx, upsertTransaction,
		arg.TxHash,
		arg.BlockHeight,
		arg.TxIndex,
		arg.TxType,
		arg.Proposer,
		arg.Sender,
		arg.Data,
	)
	return err
}

const upsertValidator = `-- name: UpsertValidator :exec
insert into validators (address, comet_address, endpoint, node_type, spid, voting_power, status, registered_at)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (address) do update set
    comet_address = excluded.comet_address,
    endpoint = excluded.endpoint,
    node_type = excluded.node_type,
    spid = excluded.spid,
    voting_power = excluded.voting_power,
    status = excluded.status,
    registered_at = excluded.registered_at,
    updated_at = now()
`

type UpsertValidatorParams struct {
	Address      string `json:"address"`
	CometAddress string `json:"comet_address"`
	Endpoint     string `json:"endpoint"`
	NodeType     string `json:"node_type"`
	Spid         string `json:"spid"`
	VotingPower  int64  `json:"voting_power"`
	Status       string `json:"status"`
	RegisteredAt int64  `json:"registered_at"`
}

func (q *Queries) UpsertValidator(ctx context.Context, arg UpsertValidatorParams) error {
	_, err := q.db.Exec(ctx, upsertValidator,
		arg.Address,
		arg.CometAddress,
		arg.Endpoint,
		arg.NodeType,
		arg.Spid,
		arg.VotingPower,
		arg.Status,
		arg.RegisteredAt,
	)
	return err
}
