package em

import "time"

// CreatePlaylistMetadata represents metadata for creating a playlist
type CreatePlaylistMetadata struct {
	Description           *string                   `json:"description,omitempty"` // max 1000 chars
	PlaylistName          string                    `json:"playlistName"`
	IsPrivate             *bool                     `json:"isPrivate,omitempty"`
	CoverArtCID           *string                   `json:"coverArtCid,omitempty"`
	License               *string                   `json:"license,omitempty"`
	Mood                  *string                   `json:"mood,omitempty"`
	ReleaseDate           *time.Time                `json:"releaseDate,omitempty"`
	DDEXReleaseIDs        map[string]string         `json:"ddexReleaseIds,omitempty"`
	DDEXApp               *string                   `json:"ddexApp,omitempty"`
	Tags                  *string                   `json:"tags,omitempty"`
	UPC                   *string                   `json:"upc,omitempty"`
	Artists               []DDEXResourceContributor `json:"artists,omitempty"`
	CopyrightLine         *DDEXCopyright            `json:"copyrightLine,omitempty"`
	ProducerCopyrightLine *DDEXCopyright            `json:"producerCopyrightLine,omitempty"`
	ParentalWarningType   *string                   `json:"parentalWarningType,omitempty"`
	IsImageAutogenerated  *bool                     `json:"isImageAutogenerated,omitempty"`
}

// CreatePlaylistRequest represents a request to create a playlist
type CreatePlaylistRequest struct {
	PlaylistID *string                `json:"playlistId,omitempty"`
	UserID     string                 `json:"userId"`
	Metadata   CreatePlaylistMetadata `json:"metadata"`
	TrackIDs   []string               `json:"trackIds,omitempty"`
}

// UploadPlaylistMetadata extends CreatePlaylistMetadata with required genre
type UploadPlaylistMetadata struct {
	CreatePlaylistMetadata
	Genre string `json:"genre"` // required for upload
}

// PlaylistTrackMetadata represents track metadata within a playlist (genre, mood, tags optional)
type PlaylistTrackMetadata struct {
	TrackMetadata
	Genre *string `json:"genre,omitempty"` // Override to make optional
	Mood  *string `json:"mood,omitempty"`  // Override to make optional
	Tags  *string `json:"tags,omitempty"`  // Override to make optional
}

// PlaylistContent represents a track entry in a playlist
type PlaylistContent struct {
	Timestamp         int64  `json:"timestamp"`
	MetadataTimestamp *int64 `json:"metadataTimestamp,omitempty"`
	TrackID           string `json:"trackId"`
}

// UpdatePlaylistMetadata represents metadata for updating a playlist
type UpdatePlaylistMetadata struct {
	Description           *string                   `json:"description,omitempty"`
	PlaylistName          *string                   `json:"playlistName,omitempty"`
	IsPrivate             *bool                     `json:"isPrivate,omitempty"`
	CoverArtCID           *string                   `json:"coverArtCid,omitempty"`
	License               *string                   `json:"license,omitempty"`
	Mood                  *string                   `json:"mood,omitempty"`
	ReleaseDate           *time.Time                `json:"releaseDate,omitempty"`
	DDEXReleaseIDs        map[string]string         `json:"ddexReleaseIds,omitempty"`
	DDEXApp               *string                   `json:"ddexApp,omitempty"`
	Tags                  *string                   `json:"tags,omitempty"`
	UPC                   *string                   `json:"upc,omitempty"`
	Artists               []DDEXResourceContributor `json:"artists,omitempty"`
	CopyrightLine         *DDEXCopyright            `json:"copyrightLine,omitempty"`
	ProducerCopyrightLine *DDEXCopyright            `json:"producerCopyrightLine,omitempty"`
	ParentalWarningType   *string                   `json:"parentalWarningType,omitempty"`
	Genre                 *string                   `json:"genre,omitempty"`
	PlaylistContents      []PlaylistContent         `json:"playlistContents,omitempty"`
}

// UpdatePlaylistRequest represents a request to update a playlist
type UpdatePlaylistRequest struct {
	UserID     string                 `json:"userId"`
	PlaylistID string                 `json:"playlistId"`
	Metadata   UpdatePlaylistMetadata `json:"metadata"`
}

// UploadPlaylistRequest represents a request to upload a playlist with tracks
type UploadPlaylistRequest struct {
	UserID         string                  `json:"userId"`
	Metadata       UploadPlaylistMetadata  `json:"metadata"`
	TrackMetadatas []PlaylistTrackMetadata `json:"trackMetadatas"`
}

// PublishPlaylistRequest represents a request to publish a playlist
type PublishPlaylistRequest struct {
	UserID     string `json:"userId"`
	PlaylistID string `json:"playlistId"`
}

// AddTrackToPlaylistRequest represents a request to add a track to a playlist
type AddTrackToPlaylistRequest struct {
	UserID     string `json:"userId"`
	PlaylistID string `json:"playlistId"`
	TrackID    string `json:"trackId"`
}

// RemoveTrackFromPlaylistRequest represents a request to remove a track from a playlist
type RemoveTrackFromPlaylistRequest struct {
	UserID     string `json:"userId"`
	PlaylistID string `json:"playlistId"`
	TrackIndex int    `json:"trackIndex"`
}

// DeletePlaylistRequest represents a request to delete a playlist
type DeletePlaylistRequest struct {
	UserID     string `json:"userId"`
	PlaylistID string `json:"playlistId"`
}

// FavoritePlaylistMetadata represents metadata for favoriting a playlist
type FavoritePlaylistMetadata struct {
	IsSaveOfRepost bool `json:"isSaveOfRepost"`
}

// FavoritePlaylistRequest represents a request to favorite a playlist
type FavoritePlaylistRequest struct {
	UserID     string                    `json:"userId"`
	PlaylistID string                    `json:"playlistId"`
	Metadata   *FavoritePlaylistMetadata `json:"metadata,omitempty"`
}

// UnfavoritePlaylistRequest represents a request to unfavorite a playlist
type UnfavoritePlaylistRequest struct {
	UserID     string `json:"userId"`
	PlaylistID string `json:"playlistId"`
}

// RepostPlaylistMetadata represents metadata for reposting a playlist
type RepostPlaylistMetadata struct {
	IsRepostOfRepost bool `json:"isRepostOfRepost"`
}

// RepostPlaylistRequest represents a request to repost a playlist
type RepostPlaylistRequest struct {
	UserID     string                  `json:"userId"`
	PlaylistID string                  `json:"playlistId"`
	Metadata   *RepostPlaylistMetadata `json:"metadata,omitempty"`
}

// UnrepostPlaylistRequest represents a request to unrepost a playlist
type UnrepostPlaylistRequest struct {
	UserID     string `json:"userId"`
	PlaylistID string `json:"playlistId"`
}

// SharePlaylistRequest represents a request to share a playlist
type SharePlaylistRequest struct {
	UserID     string `json:"userId"`
	PlaylistID string `json:"playlistId"`
}
